### ISSUE TITLE
Want help

### ISSUE THREAD

**Issue by jimmywarting** [jimmywarting/StreamSaver.js#1]
This is very much experimental but i would like to get help building this - it's just bear and bones but the fundamental part is already there 😃 

@eligrey are you interested?

Here is a working demo https://jimmywarting.github.io/StreamSaver.js/example.html
Make sure to enable streams first:
chrome://flags/#enable-experimental-web-platform-features

**Comment by eligrey** [comment]
My company is actually working on a commercial project involving these technologies, but for a different purpose :smiley:. I'm going to look at your code tomorrow (busy atm).

I'm going to be very busy the next two weeks as I'm currently in the process of moving all of my belongings to San Francisco from the US east coast, so sorry about that. When I get free time here and there I will definitely help you out!

**Comment by eligrey** [comment]
Still getting situated in SF, sorry about that! I'll be around to help you in 2 weeks or so.
