### ISSUE TITLE
Browser compatibility table

### ISSUE THREAD

**Issue by ArturPrzybysz** [jimmywarting/StreamSaver.js#104]
In previous version on readme.md there was available browser compatibility table.
Recently it was deleted; does it mean that now any browser is able to use StreamSaver?

**Comment by jimmywarting** [comment]
I removed it b/c we now do a progressive degradation by building a blob url and use the good old `a[download]` so it pretty much cover all other browsers

all new browsers have support for saving something using streams, safari is still an exception doe... has everything needed but fails to save something generated by service worker (even if it's not a stream).

**Comment by ArturPrzybysz** [comment]
So I could assume StreamSaver is good to go any browser? Neat

**Comment by ahamelers** [comment]
Hi,

I see you got rid of the browser compat table as you've added fallbacks for various older browsers, but does that mean that there are now size limitations in those browsers (as in https://github.com/eligrey/FileSaver.js#supported-browsers)?
