### ISSUE TITLE
Stream API - zip many files using StreamSaver.js

### ISSUE THREAD

**Issue by avnermosh** [jimmywarting/StreamSaver.js#106]
Hi,

The StreamSaver.js README [here](https://github.com/jimmywarting/StreamSaver.js) mentions that it solves the problem of RAM size.

In the example [saving-multiple-files](https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/saving-multiple-files.html) a blob is created before enqueuing it in the readableZipStream and piping the data into the fileStream, i.e. the blob data is in the memory before piping it into the file.
If there are many blobs, couldn't the RAM be exceeded?

I have many files that I want to aggregate together and download into one zip file.
How can I do it without having to load everything to memory first?
Ideally, I would like to loop over the files and for each file, create a blob (e.g. using createObjectURL), stream it into the fileStream and then clear it from memory (e.g. using revokeObjectURL)
before attending to the next file.
Is this possible?

Thanks,
Avi

**Comment by jimmywarting** [comment]
> In the example saving-multiple-files a blob is created before enqueuing it in the readableZipStream and piping the data into the fileStream, i.e. the blob data is in the memory before piping it into the file.
If there are many blobs, couldn't the RAM be exceeded?

Files you get from eg `input[type=file]` don't necessarily counts towards memory usage. Browsers sometimes store the data on the disk sometimes to solve the RAM issue. but it's unpredictable what it dose.

The differences between my zipping and eg zip.js is that mine supports streaming where as zip.js 
- reads all blobs to typed arrays before zipping everything (meaning it holds everything in memory)

https://github.com/Stuk/jszip/pull/555

- It also has to have all the file zip entries before starting to zip everything where as mine can aggregate (take one at the time)

> I have many files that I want to aggregate together and download into one zip file.
How can I do it without having to load everything to memory first?
Ideally, I would like to loop over the files and for each file, create a blob (e.g. using createObjectURL), stream it into the fileStream and then clear it from memory (e.g. using revokeObjectURL)
before attending to the next file.
Is this possible?

Like with ReadableStream, zip-stream have a [pull](https://streams.spec.whatwg.org/#dom-underlying-source-pull) function so when zip-stream is done with one file you would have to get the next file that you would want to add to the zip. <br> You can also return a promise if getting the next file is asynchronous. 

```js
pull (ctrl) {
  return new Promise(rs => {
    getFile('something', function(entry) {
      ctrl.enqueue(entry)
      rs()
    })
  })
}
```

But it doesn't mean you have to get the file as a Blob, in fact zip-stream "don't work with files or blob's at all" it needs to be a file like object. (more importantly files with the new [`.stream()`](https://www.chromestatus.com/features/6206980857266176) support)

So to give you a more correct example i would have to know where the data is coming from and what you already got. (eg if it's just urls to be downloaded) but i will try to give you a more generic example

```js
const files = [
  ['some-folder/cat.mp4', 'https://d8d913s460fub.cloudfront.net/videoserver/cat-test-video-320x240.mp4'],
  ['some-folder/status.txt', 'https://httpbin.org/get'],
  ['some-folder/teapot.txt', 'https://httpbin.org/status/418']
].values() 
// Getting a iterator `.values()` is good for task where you
// have to iterate over values but can't use a for-loop

new ZIP({
  pull (ctrl) {
    const it = files.next()
    if (it.done) {
      ctrl.close()
    } else {
      const [name, url] = it.value

      return fetch(url).then(res => {
        ctrl.enqueue({
          name,
          stream: () => res.body
        })
      })
    }
  }
}).pipeTo(fileStream)
```

**Comment by avnermosh** [comment]
Thanks for putting the example.
In my case, the data is coming from urls to be downloaded, like in your example, so I replaced the list of files and urls from your example with the ~1000 files that I have (with a total size of ~1GB)

It worked perfectly - I was able to download a 1GB zip file, and it the files in it are identical to the original files!

I also tried the fetch example in [here](https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/fetch.html) this time on a 5GB file

In Chrome it worked ok - the size and md5sum of the downloaded file is identical to the original file.
But in Firefox I got errors 
- in the first try I got a message error 

> TypeError: The expression cannot be converted to return the specified type.

- in the second try the download completed but the downloaded file differs from the original file in size (~7.3 GB) and md5sum

I have a few questions:
1. 
I noticed your comment regarding 4 GB limit for the .zip file in [here](https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/zip-stream.js). What is the reason for this limitation? Can this limit be increased?

Given that I can aggregate the files on the server side, is there an advantage for using the [fetch](https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/fetch.html) method over the [saving-multiple-files example](https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/saving-multiple-files.html)? (in terms of complexity, reliability, performance, etc..)

Thanks

**Comment by jimmywarting** [comment]
1) yeah, that's right. It's possible to increase the size by adding support for zip64 but I don't fully understand the [spec](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) to be able to implement it.
You could deflate (compress) the content also if it's not already in a compressed format to lower the size. But that is not implemented in my zip version.

2) if you can zip the content on the server side with a streaming fashion I would most probably do so. Also make use of content disposition attachment response header so you wouldn't need streamSaver at all

**Comment by jimmywarting** [comment]
btw, Do you maybe have a fiddle example or something to demonstrate the firefox bug where the files becomes corrupted (possible with smaller files)?

**Comment by avnermosh** [comment]
I don't have a fiddle example, but the html is basically the one in (here) (fetch1)
I created the file via 
dd if=/dev/zero of=bigFile.5GB.txt count=5242880 bs=1024

Since last conversation, several more times with Firefox and the download is exact (similar md5sum) and I couldn't reproduce the error again.

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <button id="$start">Start</button>

        <script src="https://cdn.jsdelivr.net/npm/web-streams-polyfill@2.0.2/dist/ponyfill.min.js"></script>
        <!-- <script src="../StreamSaver.js"></script> -->
        <script src="./StreamSaver.js"></script>
        <script>
         $start.onclick = () => {
             const url = 'http://localhost/bigFile.5GB.txt'
             
             const fileStream = streamSaver.createWriteStream('bigFile.txt')

             fetch(url).then(res => {
                 const readableStream = res.body

                 // more optimized
                 if (window.WritableStream && readableStream.pipeTo) {
                     return readableStream.pipeTo(fileStream)
                                          .then(() => console.log('done writing'))
                 }

                 window.writer = fileStream.getWriter()

                 const reader = res.body.getReader()
                 const pump = () => reader.read()
                                          .then(res => res.done
                                                   ? writer.close()
                                                   : writer.write(res.value).then(pump))

                 pump()
             })
         }
        </script>
    </body>
</html>

```

**Comment by artemgurzhii** [comment]
@jimmywarting Is there a way to combine [split, send each part, merge splits into one file](https://github.com/jimmywarting/StreamSaver.js/issues/101) with zipping multiple files?

So what I need, is to download multiple files by multiple chunks and combine all of them into zip

**Comment by jat255** [comment]
> This example will only download one file at the time, and it's piped from url > zip > streamSaver

@jimmywarting is there a way (in this example) to keep track of how much data has passed through the stream? In my use-case, I can precalculate the size of the zip, and would like to give a javascript progress bar, but that requires being able to keep track of how much data has been piped to the `fileStream`. Any thoughts?

**Comment by coder-amogh** [comment]
@jat255 did you figure out how to do it? I'm stuck at the same place. How to get progress to show? I just tested on Chrome and it doesn't show how much file size the ZIP file is going to be. So, there is no idea to the user about the progress and there should be a way to explicitly show the progress.

**Comment by jimmywarting** [comment]
the final zip size is not compressed, so it should be possible to figure out.
it should probably be something like 

there is 3 things that's need to be calculated 
- **Every entry:** (entry header + data.size + bytes of the path) * 
- **central directory:** basically the sum of all entry headers concatenated
- **size of central directory at the very end** this is always 2 bytes at the end

**Comment by jat255** [comment]
Yes, I eventually got it working; my download function is pretty convoluted, but for the download size, I essentially just pre-fetched all the content-length values and summed them up. That seemed to work pretty well.

I can scrounge up the code, if you're interested.

**Comment by jimmywarting** [comment]
> I can scrounge up the code, if you're interested.

That would be grate!

**Comment by jat255** [comment]
> probably best if you do it with HEAD request also

Yup, that's what I'm using. 



> content-length isn't always the equivalent of the actually file size

That's interesting (I was unaware of that). It has seemed to work okay in my application so far.


The following code is _very_ hacky, so fair warning, but hopefully it will help you. I am not a javascript programmer by trade, and there are many optimizations that could be made, but this was Good Enough™. This code powers a "file downloader tool" that we have, where users can select (using DataTables) which data files they want to download, and our code takes care of bundling them up from the remote server and providing progress information to the user. It uses `Streamsaver.js` (with `zip-stream.js`, `web-streams-adapter`, and `web-streams-polyfill`) and works on Chromium-type browsers and Firefox (with the ponyfill)

Since my users may have large files, it also includes some logic that breaks up the zips so they're smaller than 4 GB, or downloads the file individually if any one is larger than 4GB. Because of this, the code is a bit repetitive in parts for ZIPs vs. individual files. Each file included in the zip also has a .json sidecar that gets zipped up along with the data file, so if you see any reference to `data_url` or `json_url`, that's what those are. Also, throughout the code I make use of `window.file_sizes`, which is an object populated when the page first loads by the `showDownloadSize()` function (included below as well). I've tried to strip out all the unnecessary bits for this demo related to my application, but there are a few references to some DataTables stuff and others that are not really important (so this code copy-pasted won't work for your application as-is, is what I'm trying to say).

To keep track of progress, I pipe the download through a custom `TransformStream`, that keeps track of how many bytes have already been downloaded, and calls another function to update the progress bar display based on how much of the total to be downloaded has already been processed. I use `streamSaver.createWriteStream` with the precomputed size so the browser-supplied progress meter works as well. I also did some stuff with `AbortController` to make it so the download can be canceled (I don't really remember how that all worked, but I eventually got it working with this implementation)

`downloadFn` is what kicks off the whole download process:

<details>
  <summary>downloadFn()</summary>
  
```javascript
// initiate download of files with their metadata
// @param {Array} data_urls : the URLs of the data files to include in zip
// @param {Array} json_urls : the URLs of the json files to include in zip
// @param {Array} paths : the containing folder of each file to include in zip
// @param {String} zip_title: the name of the .zip to download
var downloadFn = function (data_urls, json_urls, paths, zip_title) {
    updatePercent(0); //this is a function that updates my bootstrap progressbar

    // combinedObject will have items [data_url, json_url, path]
    let combinedObject = data_urls.map(function (e, i) {
        return [e, json_urls[i], paths[i]];
    });
    // combinedArray will be of type array, so it can looped through with forEach
    let combinedArray = $.map(combinedObject, function (value, index) {
        return [value];
    });

    // array of zips (not actually used besides as a counter)
    let zips = [];
    // array of total zip sizes
    let zip_total_sizes = [];
    let indiv_dl_sizes = [];
    // array of arrays listing which urls are in each zip 
    let zip_url_listing = [];
    // array of arrays listing the filepaths in each zip 
    let zip_path_listing = [];
    let cur_zip_idx = 0;
    let this_zip_size = 0;

    // limit zip size to 4.0 GiB (4294967296 bytes)
    // zips larger than 4.0 GiB are corrupted by the zip-stream.js
    // library and cannot be read, so we have to stay under that size
    const size_limit = 4294967296;

    // specify loopLength so we can change it if we need to ignore files
    var loopLength = combinedArray.length;
    var individual_files = [];
    // Allocate each url to a particular zip based on size:
    for (var index = 0; index < loopLength; index += 1) {

        let item = combinedArray[index];
        var this_data_url = item[0];
        var this_json_url = item[1];
        var this_path = item[2];

        // remove leading slash:
        if (this_path.charAt(0) === '/') {
            this_path = this_path.substr(1);
        }
        // convert url to filename
        var data_filename = this_data_url.replace(/.*\//g, "");
        var json_filename = this_json_url.replace(/.*\//g, "");
        // add appropriate path structure for the file
        if (this_path.length > 0) {
            var full_data_path = this_path + '/' + data_filename
            var full_json_path = this_path + '/' + json_filename
        } else {
            var full_data_path = data_filename;
            var full_json_path = json_filename;
        }

        // make paths like files and not like URLs
        full_data_path = decodeURIComponent(full_data_path);
        full_json_path = decodeURIComponent(full_json_path);

        // if this file is larger than the zip limit, process it separately
        // and adjust the for loop to compensate
        let this_file_size = window.file_sizes[this_data_url] +
            window.file_sizes[this_json_url];
        if (this_file_size > size_limit) {
            console.log('Adding ' + full_data_path + ' to individual file downloads');
            individual_files.push(combinedArray[index][0]);
            console.log('Adding ' + full_json_path + ' to individual file downloads');
            individual_files.push(combinedArray[index][1]);
            indiv_dl_sizes.push(window.file_sizes[this_data_url]);
            indiv_dl_sizes.push(window.file_sizes[this_json_url]);
            loopLength -= 1;
            combinedArray.splice(index, 1);
            index -= 1;
            continue;
        }

        // If this is the first file (i.e. zip size == 0), 
        // create new zip object and add it to array
        if (this_zip_size === 0) {
            zips.push({});
            zip_url_listing.push([]);
            zip_path_listing.push([]);
        }
        // this is not the first file:
        else {
            // check to make sure adding this file would not
            // put us over the zip size limit
            let new_size = window.file_sizes[this_data_url] +
                window.file_sizes[this_json_url] +
                this_zip_size;
            // if we're over the limit, end this zip, start
            // new one and repeat iteration by decrementing index
            if (new_size > size_limit) {
                zip_total_sizes.push(this_zip_size);
                this_zip_size = 0;
                cur_zip_idx += 1;
                index--;
                continue;
            }
        }

        // replace any double slashes
        full_data_path = full_data_path.replace('//', '/');
        full_json_path = full_json_path.replace('//', '/');

        // assign file to zip
        zip_url_listing[cur_zip_idx].push(this_data_url);
        zip_url_listing[cur_zip_idx].push(this_json_url);
        zip_path_listing[cur_zip_idx].push(full_data_path);
        zip_path_listing[cur_zip_idx].push(full_json_path);

        console.log('Adding', humanFileSize(window.file_sizes[this_data_url]), 'file:', full_data_path, 'to zip #:', cur_zip_idx);
        this_zip_size += window.file_sizes[this_data_url];
        this_zip_size += window.file_sizes[this_json_url];
    }
    zip_total_sizes.push(this_zip_size);

    var msg = '';
    if (zips.length > 1) {
        msg = 'Due to limitations of the .zip format, your ' + window.human_dl_size +
            ' download will be split into ' + zips.length +
            ' .zip files (each a maximum of ' +
            humanFileSize(size_limit) + ' in size). ' +
            'You can extract them all to the same ' +
            'folder to view all your data at once. \n'
        showExtraMessage(msg, 'warning');
    }

    // an array to hold async zip promises so we can do 
    // something after they all complete with Promise.all
    promList = [];
    // an array to hold each zip's percentage complete
    indiv_percs = [];
    // an array to hold each zip's downloaded bytes count
    indiv_dl_size = [];

    filesArr = [];
    for (var i = 0; i < zip_url_listing.length; i += 1) {
        filesArr.push([]);
        for (var j = 0; j < zip_url_listing[i].length; j += 1) {
            filesArr[i].push([zip_path_listing[i][j], zip_url_listing[i][j]]);
        }
    }
    // get iterators so we can do async loops
    // have to iterate over values but can't use a for-loop, due to async nature
    filesIters = filesArr.map(f => f.values());

    var bytesDownloaded = 0

    // use ponyfill if needed for TransformStream
    const TransformStream = window.TransformStream ?
        window.TransformStream : ponyfill.TransformStream;

    // create array of TransformStreams to process progress
    // while downloading
    progressArr = [];
    for (var i = 0; i < zips.length; i++) {
        p = new TransformStream({
            transform(chunk, ctrl) {
                bytesDownloaded += chunk.byteLength
                updateProgressBar(bytesDownloaded,
                    arrSum(zip_total_sizes) +
                    arrSum(indiv_dl_sizes));
                ctrl.enqueue(chunk);
            }
        });
        progressArr.push(p);
    }

    // add transformstreams for the individual file downloads
    for (var i = 0; i < individual_files.length; i++) {
        p = new TransformStream({
            transform(chunk, ctrl) {
                bytesDownloaded += chunk.byteLength
                updateProgressBar(bytesDownloaded,
                    arrSum(zip_total_sizes) +
                    arrSum(indiv_dl_sizes));
                ctrl.enqueue(chunk)
            }
        });
        progressArr.push(p);
    }

    var fileStreamArr = [];
    var readableStreamArr = [];

    var abortController = new AbortController();
    var abortSignal = abortController.signal;
    var dlError = false;

    // download zip files
    for (var i = 0; i < zips.length; i++) {
        if (zips.length === 1) {
            this_zip_title = zip_title;
        } else {
            this_zip_title = zip_title.replace(
                '.zip', '-' + (i + 1) + 'of' +
                zips.length + '.zip');
        }

        let ws = streamSaver.createWriteStream(
            this_zip_title, {
                size: zip_total_sizes[i]
            });

        fileStreamArr.push(ws);

        let files = filesIters[i];
        // ZIP is a ReadableStream
        z = new ZIP({
                pull(ctrl) {
                    const it = files.next()
                    if (it.done) {
                        ctrl.close()
                    } else {
                        const [name, url] = it.value

                        return fetch(url, {
                                signal: abortSignal
                            })
                            .then(res => {
                                ctrl.enqueue({
                                    name,
                                    stream: () => {
                                        r = res.body;
                                        readableStreamArr.push(r);
                                        return r
                                    }
                                });
                            });
                    }
                }
            }).pipeThrough(progressArr[i])
            .pipeTo(fileStreamArr[i], {
                signal: abortSignal
            })
            .catch(err => {
                if (abortSignal.aborted) {
                    console.log('[XSLT] [zip-pipeTo] User clicked cancel');
                } else {
                    console.log('[XSLT] [zip-pipeTo] Other error');
                    console.error(err);
                    dlError = true;
                    showError('There was an error during the download:', err.message);
                }
            });
        promList.push(z);
    }

    // used to convert the response of a fetch api to a modern ReadableStream with pipeThrough
    toPonyRS = WebStreamsAdapter.createReadableStreamWrapper(ponyfill.ReadableStream)

    // download large individual files
    for (var i = 0; i < individual_files.length; i++) {
        let url = individual_files[i];
        let filename = decodeURIComponent(url.replace(/.*\//g, ""));
        let fileStream = streamSaver.createWriteStream(
            filename, {
                size: window.file_sizes[url]
            }
        );
        let writer = fileStream.getWriter();
        writer.releaseLock();
        let this_prog = progressArr[i + zips.length]
        let p = fetch(url, {
                signal: abortSignal
            })
            .then(res => {
                rs = res.body;
                // use webstream adapter if we don't have pipeTo on the response (i.e. FF)
                rs = window.ReadableStream.prototype.pipeTo ?
                    rs : toPonyRS(rs)
                readableStreamArr.push(rs);
                return rs.pipeThrough(this_prog)
                    .pipeTo(fileStream,
                        // make sure this pipe is abortable
                        {
                            signal: abortSignal
                        })
                    .catch(err => {
                        if (abortSignal.aborted) {
                            console.log('[indivFile-pipeTo] User clicked cancel');
                        } else {
                            console.log('[indivFile-pipeTo] Other error');
                            dlError = true;
                            showError('There was an error during the download:', err.message);
                        }
                    });
            });
        promList.push(p);
        fileStreamArr.push(fileStream);
    }

    // Add warning if user tries to leave page before download is finished:
    // In newer browsers, this message will not show (just the "unsaved changes" warning)
    $(window).bind('beforeunload', function () {
        return 'The download has not finished, are you sure you want to leave the page?';
    });

    const cancel_downloads = function () {
        abortController.abort();
    }

    // make downloads cancel when leaving page or clicking cancel button
    window.onunload = cancel_downloads;
    $('#btn-cancel-dl').click(cancel_downloads);

    // clean up after all Promises have delivered
    Promise.all(promList).then(function () {
        // if the download was aborted:
        if (abortSignal.aborted) {
            showMessage("Download canceled by user (any already completed downloads were saved)", 'warning');
        } else if (dlError) {
            errorProgress();
        } else { // otherwise we finished normally
            finishProgress();
            showMessage("Finished downloading all files!", 'success');
        }
        $(window).unbind('beforeunload');
    });
};

```
</details>

##### `showDownloadSize` is used to display how big the download _will_ be to the user and also takes care of keeping track of the size of each file to be downloaded:

<details>
  <summary>showDownloadSize()</summary>
  
```javascript
// this is the code used to get all the file sizes
window.file_sizes = {};
//
// get the size of a group of URLs and display it to user
// @param {Array} data_urls : the URLs of the data files to query
// @param {Array} json_urls : the URLs of the json files to query
// @param {String} type : one of ['initial', 'select'] whether this is the 'initial' data size query or not (when page first loads)
//
function showDownloadSize(data_urls, json_urls, type) {
    // combinedObject will have items [data_url, json_url]
    var combinedObject = data_urls.map(function(e, i) {
        return [e, json_urls[i]];
    });
    // combinedArray will be of type array, so it can looped through with forEach
    var combinedArray = $.map(combinedObject, function(value, index) {
        return [value];
    });
    var total_size = 0;
    promList = [];
    sizeList = [];
    combinedArray.forEach(function (item, index) {
        this_data_url = item[0];
        this_json_url = item[1];
        // if we've already cached this file's size, just use that instead of fetching again
        if (this_data_url in window.file_sizes) {
            promList.push(Promise.resolve());
            let this_data_size = window.file_sizes[this_data_url]
            total_size += this_data_size;
            sizeList.push({name: this_data_url,
                            size: this_data_size});
        } else {
            data_prom = get_url_size(this_data_url);
            promList.push(data_prom);
            data_prom.then(res => {
                total_size += res.size
                sizeList.push({name: res.url,
                                size: res.size}); 
            });
        }
        // if we've already cached this file's size, just use that instead of fetching again
        if (this_json_url in window.file_sizes) {
            promList.push(Promise.resolve());
            let this_json_size = window.file_sizes[this_json_url];
            total_size += this_json_size
            sizeList.push({name: this_json_url,
                            size: this_json_size});
        } else {
            json_prom = get_url_size(this_json_url);
            promList.push(json_prom);
            json_prom.then(res => {
                total_size += res.size
                sizeList.push({name: res.url,
                                size: res.size});
            });
        }
    });
    
    Promise.all(promList).then(function() {
        var human_dl_size = humanFileSize(total_size);
        window.total_size = total_size;
        window.human_dl_size = human_dl_size;
        sizeList.map(function(v, i){
            window.file_sizes[v['name']] = v['size']})
        // if this is the initial run, update the filelisting table with sizes:    
        if ( type === 'initial' ) {
            filelist_dt.rows().every( function (rowIdx,tableLoop,rowLoop) {
                var d = this.data();
                var a = d.data_dl;
                var url = $(a)[0].href
                // use datatables cell API to set this row's 'size' column to the human file size:
                this.cell(rowIdx, 'size:name').data(humanFileSize(window.file_sizes[url]));
            });
        }
    });
}
```
</details>

##### `get_url_size` is the helper function that issues the actual `HEAD` request to get the file size:

<details>
  <summary>get_url_size()</summary>
  
```javascript
//
// get the size of a download for a url
// @param {String} url : the URLs of the data file to query
//
async function get_url_size(url) {
    let res = await fetch(url, {method:'HEAD'})
    contentlength = Number(res.headers.get('content-length'));
    return {'url': url, 'size': contentlength};
}
```
</details>

**Comment by AnhTuan-AiT** [comment]
@jimmywarting Hello jimmywarting. I really admire you and the package you have created. I am in need of the function of downloading a zip file that could be larger than 3GB in size from the server with the spring boot backend. Using stream saver, I did it on my computer but I don't know how it works, why when I press the download button the file explorer window doesn't open immediately for me to save the file And let it continue to save the stream data to the file I just created. Sorry if my expression is not good but what I want to know is the whole file saving process, when the fetch API fetches the stream data from the server and saves it to the file system on the client. Thank you so much

**Comment by dferrazm** [comment]
Hey @jimmywarting thanks for the work so far. I'm a bit new on the JS Stream API and trying to get my head around it. My scenario is basically similar to others: I have a bunch of files that come from the server encrypted, decrypt'em on client side and zip'em to be downloaded by the user.

I had a 'partial' success using your [snippet](https://github.com/jimmywarting/StreamSaver.js/issues/106#issuecomment-505369974). When this is called `readableZipStream.pipeTo(fileStream)`,  the file is created and starts to build iteratively.

Problem is that the native dialog (eg on FF) asking the where to save is triggered right after that call above and the zip stream begins even before, when the user hasn't confirmed the dialog yet.

Is there a way to start the zip stream only after the user has confirmed the dialog which asks where to store the file?

**Comment by jimmywarting** [comment]
@dferrazm
> Is there a way to start the zip stream only after the user has confirmed the dialog which asks where to store the file?

Yes and no. Not so much with StreamSaver, but another native tool can help out with this.

I see two solutions to this.

1. **First option** is less elegant it still involves triggering a download with partial data downloaded from your api. You can't trigger a download/save dialog without making an actual request/response with `content-disposition` attachment header. But you would let this temporary bucket fill up with small bits of data using something like a [QueueStratergy](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Concepts#internal_queues_and_queuing_strategies). Then when the write operator is done writing the small bits it has in the memory then it would call the ReadableStreams pull method to ask for more data, so it would not request more data than what's in the pipeline
  - This is unfortunately not well handled from the start in StreamSaver. The Service Worker don't pull any data. The data is transfered from main thread to service worker via postMessages and written to the download stream as soon as possible - so it's possible to overflow the bucket if it can append data faster than what it can write to the disk.
  - But that is just one of the two option the data is transfered. The other one is with [Transferable ReadableStreams](https://chromestatus.com/feature/5298733486964736) and using pipe's. This allows data to flow from point a to point b seemingly, It also means that if you pause the download -> then the bucket gets full -> and it would pause the request being made. This method is preferred over postMessaging but not something you have control over. it's done with feature detection
  
You can see/detect when this bucket gets full and take action, a example of this is the https://jimmywarting.github.io/StreamSaver.js/examples/torrent.html demo. if you pause the download you will start to see that desired size drops b/c you are filling the bucket too much. But not all browser supports this Transferable ReadableStream method.

---

2. **Second option** would be to use the new [File System Access](https://wicg.github.io/file-system-access/) here you have grater tools to first ask for write permission, what file format they want to save it in. And even write multiple files to a folder handle that you have requested write permission to without having to zip everything. If they haven't selected a place or rejected the dialog, then you will know that it have been canceled and no api request have to be made at all. The unfortunate part doe is that it isn't wildly adapted by many browser yet and is still very experimental.
I expect one day that the File System Access will overtake this StreamSaver lib and other alike in the feature since it's a spec'ed browser thing. but i don't see that happening soon.

I have however written an adapter/polyfill to this new file system access to speed up the process. It also utilizing service worker to trigger a download just like StreamSaver but it solves the issue with the ReadableStreams pull source from the gecko. It's instead based on the readableStreams pull method. 
So when you call `await writer.write(data)` then you can rest to sure that the data have been added to the bucket without overflowing the bucket and is soon close to being written to the harddrive instead of just blindly postMessage it to the service worker without having no knowledge of the bucket like how it's being done in StreamSaver.
And you don't have to rely on some MITM service worker since data is directly transfered to the service worker (it just makes it a tiny bit more complicated to set it up)
Have a look at it if you want to try it out: https://github.com/jimmywarting/native-file-system-adapter
I can help you out if you get into any problems using it.

**Comment by dferrazm** [comment]
Thansk for all the detailed explanation @jimmywarting !! I'm still going over it and trying to absorb everything there, since a few of the concepts are still new to me.

I"ll let you what comes out of it or in case I need additional help. Thanks again.
