### ISSUE TITLE
Browser compatibility list 

### ISSUE THREAD

**Issue by cryingbat** [jimmywarting/StreamSaver.js#109]
where is Browser compatibility list？i Cannot  find it？

**Comment by jimmywarting** [comment]
Haven't made one... (or rather i had one basic in the readme [before](https://github.com/jimmywarting/StreamSaver.js/blob/da6218e2a58bcc4b0ba997c53d605dd096ba02c3/README.md), but took it away when i added the blob writer fallback)

It works in all latest browsers at least.

it has a fallback solution to where it writes a stream to a blob file and later create a objectURL and saves it very much similar to FileSaver.js dose it but except it don't use `msSaveOrOpenBlob` 
safari has all the compatibility features for it to work but dose something wrong internally so it is hardcoded to use the blob fallback. still haven't done a feature detection yet (#69)

it's also written in es6 without any compiling so there is that...

I will not dig into what the lowest supported browser is but i will accept a PR if you are willing to dig into it

**Comment by cryingbat** [comment]
hi, i have a question, in ff 66.0.5 (64 位) .   i use streamSaver but i got  ``streamSaver.WritableStream is not a constructor ``  this error; i try to use ponyfill.min.js ;but  not resolve.i want to konw why?and how to do it?

**Comment by jimmywarting** [comment]
do you have a fiddle, plunkr or other playground or code example to show?

basically 
- load the stream ponyfill
- load streamsaver
- assign writablestream to streamsaver
```js
streamSaver.WritableStream = ponyfill.WritableStream
```

**Comment by jbelien** [comment]
I have the same issue as you @cryingbat ; how did you fix it ? Thanks!

**Comment by cryingbat** [comment]
> I have the same issue as you @cryingbat ; how did you fix it ? Thanks!

do you have try to import 'ponyfill.min.js';or <script src = 'ponyfill.min.js'></script>.  this can fixed it;

**Comment by subins2000** [comment]
I used this :
```
import * as ponyfill from 'web-streams-polyfill/ponyfill'
streamSaver.WritableStream = ponyfill.WritableStream
```
