### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by RobPethick** [jimmywarting/StreamSaver.js#111]
Is it possible to use this in Typescript? I can't find a set of typings here or in @types/streamsaver

**Comment by jimmywarting** [comment]
> Is it possible to use this in Typescript? 

sure, any javascript works with TypeScript (but not the other way around).

---

I'm not comfortable working with typescript. 
https://github.com/cross-js/cross-js#dont-use-anything-else-then-javascript

However i'm willing to accept a PR that includes a `.d.ts` file

I use doc annotation and some IDE are able to use it as well as typescript is able to parse TS code.
if i'm not mistaking TS should handle doc annotation as well? or maybe it was Flow... don't remember.
