### ISSUE TITLE
download crashed after 2GB

### ISSUE THREAD

**Issue by bhargav19** [jimmywarting/StreamSaver.js#112]
Im trying to download a large file of 5gb file through StreamSaver.js but it crashes after reaching 2 GB.
Please help me out on this. 

here is part of code snippet i am using
```js
const streamSaver = require('streamsaver');

// using streamSaver 
const fileStream = streamSaver.createWriteStream(fileName);
const readableStream = res.body  // res is response from the fetch api


    if(window){
      // more optimized
      if (window.WritableStream && readableStream.pipeTo) {
        return readableStream.pipeTo(fileStream)
      }

      window.writer = fileStream.getWriter()      
    }
```

**Comment by jimmywarting** [comment]
What browser are you using?

**Comment by bhargav19** [comment]
Cheome

**Comment by jimmywarting** [comment]
hmm, tried Chrome v76
had no problem saving 3.15 gb of lorem data using this demo
https://jimmywarting.github.io/StreamSaver.js/examples/plain-text.html

might have more Ram

**Comment by jimmywarting** [comment]
Are you using a secure origin?

Dose it work to save 2gb+ with this demo?
https://jimmywarting.github.io/StreamSaver.js/examples/plain-text.html
