### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by cryingbat** [jimmywarting/StreamSaver.js#118]
i upgrade the streamsaver from 1.xx  to 2.0.3. before everything  is ok .when i upgrade,  the download progress is ok ,but the filename can not show, i see the chrom download show undifined file,    upgrade:  before   i have five file 1.mitm.html  2.ping.html 3.ping.js 4.streamsaver.js 5.sw.js.   after i have 3 file  1.mitm.html 2.streamsaver.js  3.sw.js  .   now i do not know  where  are wrong   

use: 
```html
<script type="text/javascript" src="StreamSaver.js"></script>
```
```js
fileStream = streamSaver.createWriteStream(filename + '.264');
var writer = fileStream.getWriter();
var fr = new FileReader();
var chunks = Promise.resolve();

chunks = chunks.then(() => new Promise(resolve => {
  fr.onload = () => {
      writer.write(protobuf.getVideoBuffer())
      resolve()
  }
  fr.readAsArrayBuffer(buffer)
}))
```

**Comment by cryingbat** [comment]
hello！ this question have something resolve？

**Comment by jimmywarting** [comment]
sorry, i don't know whats wrong... do you have some jsfiddle example?
