### ISSUE TITLE
Can we write file with UTF-16/ UCS-2 encoding

### ISSUE THREAD

**Issue by nakshay** [jimmywarting/StreamSaver.js#121]
Is there any way to write file encoded with UTF-16/UCS-2 encoding?

**Comment by jimmywarting** [comment]
can you show some code example?

**Comment by nakshay** [comment]
Hello @jimmywarting , 
below SO question will give you more details.
[stackoverflow](https://stackoverflow.com/questions/58093003/how-to-write-csv-file-with-utf-16-and-bom)

**Comment by jimmywarting** [comment]
I would just change the way you get the data.
when you use text/json the browser will try to be smart and encode/decode the charset to something else

as with xhr and angular you have the option to return it as arrayBuffer or a blob by changing the responseType
with fetch you would use something like `await res.blob()`
then you can save the file with fileSaver without creating the blob yourself.
then you will get exactly the data that the server is responding with (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data)

if you want to use streamSaver then have a look at the fetch example: https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/fetch.html

fileSaver and streamSaver have no problem saving any file in any encoded format, it's up to you to give it the right data that it should write to the disk.

**Comment by jimmywarting** [comment]
also text/csv and json is not the same.

**Comment by jimmywarting** [comment]
https://github.com/eligrey/FileSaver.js/wiki/Saving-a-remote-file#diffrent-ajax-methods
