### ISSUE TITLE
 Huawei browser kernel is Netscape, this kernel can not be downloaded

### ISSUE THREAD

**Issue by scartf** [jimmywarting/StreamSaver.js#124]
Huawei browser kernel is Netscape, this kernel can not be downloaded

**Comment by jimmywarting** [comment]
what?

**Comment by eligrey** [comment]
@scartf you can find the source code to the Huawei browser Netscape kernel at [https://www.huawei.com/en/docs/netscape-kernel-download](https://www.youtube.com/watch?v=oHg5SJYRHA0).

**Comment by scartf** [comment]
> what?

The core of the mobile phone browser is Netscape, and its browser can not be downloaded with StreamSaver.

**Comment by jimmywarting** [comment]
Do you have problem using streamsaver in the Huawei browser?
or do you have problem downloading the kernel using any other browser + StreamSaver?

I don't have any Huawei mobile or Huawei browser so i can test it.
you have to provide some more errors/logs possible a code example as well.

Dose the browser have native ReadableStream, fetch & Service Workers?
Dose FileSaver.js works for you? (a.k.a: `<a href="" download="">)?

And why bother with such a old browser like Netscape? but is it really using Netscape? are you sure that it just isn't a shell like with Edge and Opera (they use a webview and runs on the Blink engine in the background)

----

Your question is very unclear.
it's like saying: *"I have created a css file but my DOM element dose not change."*

it's a statement and not a question. And the reason could be many, you haven't included the `<link>`, you are missing `rel="stylesheet", `your `@import` is wrong, you don't match the css selector, some other rule overrides it or the browser dose not support the style property.

you see if i should be able to help you then you need to describe your issue more clearly.

**Comment by jimmywarting** [comment]
Also dose this example works for you in your browser?
https://jimmywarting.github.io/StreamSaver.js/examples/write-slowly.html

take a printscreen and upload it here

**Comment by scartf** [comment]
1、I have a  problem using streamsaver in the Huawei browser.
[https://cdn.o2omed.com/WechatIMG1090.jpeg](url)
[https://cdn.o2omed.com/WechatIMG1088.jpeg](url)
[https://cdn.o2omed.com/WechatIMG1089.jpeg](url)
2、https://jimmywarting.github.io/StreamSaver.js/examples/write-slowly.html
====》Invalid start click in this link
3、Huawei has many mobile phones in China, so they must be adapted.
4、I'm sorry for my English is poor.

**Comment by scartf** [comment]
@jimmywarting

**Comment by scartf** [comment]
> @scartf you can find the source code to the Huawei browser Netscape kernel at [https://www.huawei.com/en/docs/netscape-kernel-sources](https://www.youtube.com/watch?v=oHg5SJYRHA0).

thank you

**Comment by scartf** [comment]
> Do you have problem using streamsaver in the Huawei browser?
> or do you have problem downloading the kernel using any other browser + StreamSaver?
> 
> I don't have any Huawei mobile or Huawei browser so i can test it.
> you have to provide some more errors/logs possible a code example as well.
> 
> Dose the browser have native ReadableStream, fetch & Service Workers?
> Dose FileSaver.js works for you? (a.k.a: `<a href="" download="">`)?
> 
> And why bother with such a old browser like Netscape? but is it really using Netscape? are you sure that it just isn't a shell like with Edge and Opera (they use a webview and runs on the Blink engine in the background)
> 
> Your question is very unclear.
> it's like saying: _"I have created a css file but my DOM element dose not change."_
> 
> it's a statement and not a question. And the reason could be many, you haven't included the `<link>`, you are missing `rel="stylesheet", `your `@import` is wrong, you don't match the css selector, some other rule overrides it or the browser dose not support the style property.
> 
> you see if i should be able to help you then you need to describe your issue more clearly.

Other browsers such as Google and safari test are good
1、I have a problem using streamsaver in the Huawei browser.
https://cdn.o2omed.com/WechatIMG1090.jpeg
https://cdn.o2omed.com/WechatIMG1088.jpeg
https://cdn.o2omed.com/WechatIMG1089.jpeg
2、https://jimmywarting.github.io/StreamSaver.js/examples/write-slowly.html
====》Invalid start click in this link
3、Huawei has many mobile phones in China, so they must be adapted.
4、I'm sorry for my English is poor.
