### ISSUE TITLE
huaiwei、baidu、qq Browser Huawei browser will fail to download

### ISSUE THREAD

**Issue by scartf** [jimmywarting/StreamSaver.js#125]
First of all, thank you for your github. When we use your blob test code, it can be used in our computer browser successfully, and also in mobile iphone's safari. However, in Huawei's mobile browser, it jumps out a download dialog box and shows file size, correct file name. But the download will fail. In the google inspect software, we can see that the console.log ('done writing') is executed. Some documents are attached to the link, please help and support, thank you very much.
https://cdn.o2omed.com/WechatIMG1090.jpeg
https://cdn.o2omed.com/WechatIMG1088.jpeg
https://cdn.o2omed.com/WechatIMG1089.jpeg

**Comment by jhabdas** [comment]
> Huawei's mobile browser, it jumps out a download dialog box and shows file size, correct file name.

I have a P30 Pro with Huawei browser if you need someone to test please hand me a reduced test case because I'd like to see if "Huawei browser" (which is _mostly_ open source IIRC 😅) can't do it if Vivaldi beta can.
