### ISSUE TITLE
Does this lib works without internet connection?

### ISSUE THREAD

**Issue by mobilekosmos** [jimmywarting/StreamSaver.js#126]
"So StreamSaver creates a own man in the middle that installs the service worker in a secure context hosted on github static pages."

Based on above from the main page isn't clear now how this lib works, I expected a lib that would work locally without internet connection, so this is not the case?

**Comment by blubbll** [comment]
The mitm is just a html file. The serviceworker just a javascript. You can host both offline.

**Comment by jimmywarting** [comment]
service worker is built for taking your PWA offline so it could be possible to cache mitm after the service worker have been installed and then after that it will work offline, but it isn't implemented...

One possible reason why I haven't done it yet might just be that it's lazy loaded on demand. and it isn't installed right away when you visit the site.

The alternative is what @blubbll mention host both files yourself. And configure StreamSaver to use it's own mitm `streamsaver.mitm = '/my-mitm.html'` so it works on localhost and no connection will ever be needed. 

but if you are building a semi-offline with app with service worker and that is installed once someone visit your site then you could try to embed sw.js into your own service worker and kinda merge them togheter somehow.
