### ISSUE TITLE
The torrent example fills the RAM completely

### ISSUE THREAD

**Issue by wbulot** [jimmywarting/StreamSaver.js#127]
Hi Everyone,

From the description I understand that this library save downloads data directly in filesystem instead of using the browser's RAM, which is exactly what I need. I want to use it with webtorrent to download large file from the browser and I see that there is an example on the github.

So I have tested this example : https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/torrent.html by modifying it a bit to download a 5GB torrent.

But I can notice that the whole file is still stored in RAM.
Is this the normal behavior ? Do I miss something ?

Thank you for the help.

**Comment by jimmywarting** [comment]
That isn't streamsavers fault. My torrent example is not configured to use any other "abstract chunk storage" so WebTorrent keeps all data in the memory using the "Memory chunk store"

you would have to kinda delete all the downloaded chunks once it is saved throught streamsaver...

**Comment by wbulot** [comment]
Hi @jimmywarting . Thank you for your answer.
Is it something that can be done easily from your torrent example ? I'm kind of noob about javascript filesystem and data.

**Comment by jimmywarting** [comment]
maybe take a look at https://github.com/mafintosh/abstract-chunk-store if it might help
and https://webtorrent.io/docs
