### ISSUE TITLE
can I download multiple files at the same time？

### ISSUE THREAD

**Issue by jinshengli** [jimmywarting/StreamSaver.js#130]
I had a problem downloading multiple files in a loop. The firefox Browser error:
TypeError: The stream (in closed state) is not in the writable state and cannot be closed.

I can only download the  first file. After that faile.  I canot find a good way 

my code:

url: [ {fileName: url } ]
```js
getDownFile: function(url, fileName) {
    let u = url[fileName];
    let fileStream = streamSaver.createWriteStream(fileName);
    fetch(u).then(res => {
      const readableStream = res.body;
      // more optimized
      if (window.WritableStream && readableStream.pipeTo) {
        return readableStream.pipeTo(fileStream)
          .then(() => console.log('done writing'))
      }
      window.writer = fileStream.getWriter();
      const reader = res.body.getReader();
      const pump = () => reader.read()
        .then(res => res.done ?
          writer.close() :
          writer.write(res.value).then(pump));
      pump();

    })
}

for (var fileName in url) {
  vm.getDownFile(url, fileName);
}
```

**Comment by jimmywarting** [comment]
Try changing this:
```diff
-      window.writer = fileStream.getWriter();
+      const writer = fileStream.getWriter();
```

ps, if you like you could try the [saving-multiple-files](https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/saving-multiple-files.html) example and save everything as one zip file

**Comment by jinshengli** [comment]
Thank you. It work.

**Comment by amiaynara** [comment]
> ```js
> et fileStream = streamSaver.createWriteStream(fileName);
> ```

@jinshengli the change suggested by @jimmywarting work( changing `window.writer` to `writer`)? Or did you use the [saving-multiple-files](https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/saving-multiple-files.html) this instead?

**Comment by Lwdthe1** [comment]
This worked for me with the suggested typo fix
