### ISSUE TITLE
Windows can't extract the generated zip file

### ISSUE THREAD

**Issue by ncfuncion** [jimmywarting/StreamSaver.js#137]
Hello! I tried the example in this page (saving multiple files to zip)
https://jimmywarting.github.io/StreamSaver.js/examples/saving-multiple-files.html

It generates the zip file  but Windows can't extract the file - it says the compressed file is invalid.
Why?

**Comment by jimmywarting** [comment]
https://github.com/jimmywarting/StreamSaver.js/issues/119 related maybe?

Believe I have edit the code example in the master branch but haven't merged it into gh-pages (possible)

**Comment by ncfuncion** [comment]
Yes, thank you.

**Comment by jimmywarting** [comment]
closed by #140
