### ISSUE TITLE
StreamSaver Not Defined Error

### ISSUE THREAD

**Issue by SetV** [jimmywarting/StreamSaver.js#14]
Hi,

I am trying to use StreamSaver with AngularJS. When I try to load the page, I am getting `ReferenceError: streamSaver is not defined` error. I used Chrome v53 as the browser. I can successfully execute the example code and download a 10MB file. I am not sure what I am missing.

    <script src="StreamSaver.js"></script>
    <script src="https://rawgit.com/jimmywarting/browser-su/master/build/permissions.js"></script>
    <script src="https://wzrd.in/standalone/web-streams-polyfill@1.1.1"
        integrity="sha384-8EYry4yokV53rGHMFtPqeVlAPgxn8yxr/RvxC4bZt3vlneaDPzWkSJCvBDBTuXAV"
        crossorigin>
    </script>
    <script>
        !streamSaver.supported && prompt(
            'ReadableStream is not supported, you can enable it in chrome, or wait until v52',
            'chrome://flags/#enable-experimental-web-platform-features'
        )
    .........
    </script>

**Comment by jimmywarting** [comment]
Do you have something like require.js or any other module loader include as well?

**Comment by SetV** [comment]
AngularJS files are loaded not `require.js`.

**Comment by jimmywarting** [comment]
Most be doing something wrong. cuz this [jsfiddle](https://jsfiddle.net/hwdk2v3b/1/) works just fine

```html
<script src="https://cdn.rawgit.com/jimmywarting/StreamSaver.js/master/StreamSaver.js"></script>
<script src="https://rawgit.com/jimmywarting/browser-su/master/build/permissions.js"></script>
<script src="https://wzrd.in/standalone/web-streams-polyfill@1.1.1"
    integrity="sha384-8EYry4yokV53rGHMFtPqeVlAPgxn8yxr/RvxC4bZt3vlneaDPzWkSJCvBDBTuXAV"
    crossorigin>
</script>
<script>
    !streamSaver.supported && prompt(
        'ReadableStream is not supported, you can enable it in chrome, or wait until v52',
        'chrome://flags/#enable-experimental-web-platform-features'
    )
	alert(typeof streamSaver)
</script>
```
I got an alert with `object`

Do you get any `404 - not found` when trying to load StreamSaver.js?

**Comment by SetV** [comment]
The error is not seen after referring `StreamSaver.js` as below

`<script src="https://cdn.rawgit.com/jimmywarting/StreamSaver.js/master/StreamSaver.js"></script>`
 
Thanks!

**Comment by jimmywarting** [comment]
just a heads up
If you load it from rawgit then it means you will always use the latest from the master branch

You should maybe download StreamSaver.js to you local environment...

**Comment by SetV** [comment]
Ok Thanks! Will do that till a NPM module is available.

One quick question, How does `permissions.js` and `web-streams-polyfill` relates with`StreamSaver.js`? Do I need to save and refer the local copy?

**Comment by jimmywarting** [comment]
permissions.js doesn't relate what so ever to streamsaver.js


I don't think you even need it. 
I used it in the [example](https://jimmywarting.github.io/StreamSaver.js/example.html) to request permission for video and/or audio to show others that it can write to the disk while it's recording

permissions.js is called [browser-su](https://github.com/jimmywarting/browser-su) and it helps you to get/know permission for all kind of stuff

**Comment by jimmywarting** [comment]
I have actually planed to release a NPM module #6 So it would be grate if you didn't took that away from me, since i'm also the one who is going to have to update it
