### ISSUE TITLE
StreamSaver 404 error when dev tools open with Chrome browser

### ISSUE THREAD

**Issue by Fruko** [jimmywarting/StreamSaver.js#142]
I noticed that when we are trying to download a file via StreamSaver.js with developer tools open it fails.

to reproduce:
1) go to: https://jimmywarting.github.io/StreamSaver.js/examples/saving-a-blob.html
2) try to download sample.txt without developer tools open and see file downloaded
3) open dev tools
4) try download again -> see error
![image](https://user-images.githubusercontent.com/10186522/75147079-cbd98900-56fc-11ea-9fd8-7504bd7d7f25.png)

**Comment by jimmywarting** [comment]
this might be a case of "Bypass for network" option in your devtool.

<img width="327" alt="Skärmavbild 2020-02-24 kl  20 24 25" src="https://user-images.githubusercontent.com/1148376/75183897-b89ddc00-5743-11ea-9a51-2a58dad42e59.png">

cuz it work for me with the devtool open and when it was unchecked.
when i checked it, it failed for me also

**Comment by jimmywarting** [comment]
as you might have guessed already by the readme: streamsaver uses service workers to download content in a streaming mode

**Comment by Fruko** [comment]
Thanks @jimmywarting for clarification!
