### ISSUE TITLE
Media stream example not working

### ISSUE THREAD

**Issue by steveellis** [jimmywarting/StreamSaver.js#143]
Great stuff!

Just noticing that the media stream example wants there to be a button with the id "$close" which would prompt the stream to get written. Seems like the live example won't work without it.

This is the file: https://jimmywarting.github.io/StreamSaver.js/examples/media-stream.html

**Comment by jimmywarting** [comment]
hmm, thanks for notice. Was a long time ago since i splited the examples up to separate files - most have been broken a long time now ^^

Either way - i think i have solved it. don't have cam or mic on my mac mini so can't test it.
(only updated on gh-pages - not on master)

**Comment by steveellis** [comment]
Thanks for the quick response @jimmywarting!

I was able to test the fix on my macbook. Seeing a new issue though. Seems that writable.close() isn't a function on TransformStream. I'm testing it on Chrome 80.0.3987.87 (Official Build) (64-bit).

![image](https://user-images.githubusercontent.com/104455/76107914-9f98f480-5fa7-11ea-903a-6c27be6a3527.png)

Any ideas? Happy to do more testing.

**Comment by jimmywarting** [comment]
hi @steveellis, Maybe try 
```diff
- writable.close()
+ writer.close()
```

**Comment by steveellis** [comment]
@jimmywarting you're right. Closing writer instead of writable works. Was able to run a successful test with one more change. Needed to delay the call to writer.close() like this

```
 setTimeout(function() {
  writer.close()
}, 1000);
``` 

since it looks like the ```ondataavailable``` event fires after the recording stops since I'd guess the MediaRecorder buffer has data in it and has to go somewhere. I'd hope there's a better way to handle this rather than setTimeout.

@jimmywarting I'll leave this open as a reminder to update the example. Thanks for the cool stuff!

**Comment by jimmywarting** [comment]
https://github.com/jimmywarting/StreamSaver.js/blob/2f6c53eb63adbed503651341be2987dd1cab53b1/examples/media-stream.html#L39-L43

yea... about that timeout... i had it before also. it should work to close the stream immediately i think all chunks that are left should be piped... 
reading this hole stream should still yield abc... but i have no clue what's going on there.
