### ISSUE TITLE
Questions about compatible firefox browser

### ISSUE THREAD

**Issue by hushiyun1994** [jimmywarting/StreamSaver.js#146]
I am writing a web version to transfer files.After the sender reads the file by streaming, the data is sent to the receiver using webrtc, and the receiver downloads the file by streaming.TransformStream and ReadableStream.pipeTo() is not supported in firefox.What should i do？Thank you very much.
```
const {readable, writable} = new TransformStream({  
  transform: (chunk, controller) => {  
    controller.enqueue(new Uint8Array(chunk))  
  }  
});  
const writer = writable.getWriter();  
readable.pipeTo(streamSaver.createWriteStream(fileName);  
//Write received chunk  
writer.write(chunk);
```

**Comment by jimmywarting** [comment]
Load a web stream polyfill version and do something like this:
```html
<script src="https://cdn.jsdelivr.net/npm/web-streams-polyfill@2.0.2/dist/ponyfill.min.js"></script>
<script>
const ponyfill = window.WebStreamsPolyfill || {}
const TransformStream = window.TransformStream || ponyfill.TransformStream
</script>
```

And also 
- Give [MattiasBuelens/web-streams-polyfill](https://github.com/MattiasBuelens/web-streams-polyfill) a well deserved github ⭐️ 
- give this [web-streams-polyfill#20 issue](https://bit.ly/2WGEFjZ) a 👍

**Comment by jimmywarting** [comment]
Would also be cool if you tried this https://github.com/jimmywarting/native-file-system-adapter also instead. with it you can write more types of chunks (including blob's file's arraybuffer, arraybufferviews and strings)

**Comment by hushiyun1994** [comment]
I have given web-streams-polyfill and StreamSaver.js stars and agreed with the answer.I have implemented reading and writing of large files on electron.It's so easy.But browser security policies and differences between browser cores can be daunting.Your thinking is exciting!He helped me a lot!

**Comment by hushiyun1994** [comment]
The question now is backpressuring in streams.Reading is always much faster than writing.I try to let receiver pauses receiving data when  it has received more than 100M data ^_^

**Comment by hushiyun1994** [comment]
@jimmywarting Excuse me.One more question...In addition to my  method,adding data directly to readablestream looks simpler.But the transmission speed is about the same.Which method should I use?
```
const readable = new ReadableStream({
  pull(controller) {
    //when received chunk
    controller.enqueue(chunk)
  }
});
readable.pipeTo(streamSaver.createWriteStream(this.fileList[this.currentFileIndex].name, {
  size: this.fileList[this.currentFileIndex].size
}));
```

**Comment by jimmywarting** [comment]
Thanks for giving it stars.
Take the one you prefer. 

regarding the backpressur - there is room for improvement of it in streamsaver -  here is a more recent discussion about it: #145
