### ISSUE TITLE
some doubts about the configuration part of readme.md

### ISSUE THREAD

**Issue by hushiyun1994** [jimmywarting/StreamSaver.js#147]
Is it here to configure compatibility?The code should be：？
```javascript
streamSaver.WritableStream = WebStreamsPolyfill.WritableStream;
streamSaver.TransformStream = WebStreamsPolyfill.TransformStream
```

**Comment by jimmywarting** [comment]
if you load web streams polyfill in any other way but the cdn then yes.

if you include this 
```html
<script src="https://cdn.jsdelivr.net/npm/web-streams-polyfill@2.0.2/dist/ponyfill.min.js"></script>
```
and the `window.WebStreamsPolyfill` becomes available streamsaver can detect it and use it automatically

https://github.com/jimmywarting/StreamSaver.js/blob/a6ec1df37593c29a4b172ebc85d4038aae812c9c/StreamSaver.js#L15

**Comment by hushiyun1994** [comment]
@jimmywarting Thank you for your answer！In my free time I will read and learn the source code.
