### ISSUE TITLE
fetch example code to angularjs

### ISSUE THREAD

**Issue by SetV** [jimmywarting/StreamSaver.js#15]
I have converted the `fetch` example code to angularjs syntax. However the url file is not dowloaded. I guess the `done` value was not set anytime and the tab allocates as much memory as possible.

    $scope.file = streamSaver.createWriteStream("filename.txt");

    fetch(url).then(function(res) {
        var reader = res.body.getReader();
        $scope.pump = function(file, reader) {
            return reader.read().then(function(value, done) {
                if (done) {
                    file.close();
                    return;
                }
                file.write(value);
                return $scope.pump(file, reader);
            });
        };
        $scope.pump($scope.file, reader);
    });

**Comment by jimmywarting** [comment]
Actually this es6 code: 
```javascript
.then(({ value, done }) =>
```
will be resulted in this when converting it to es5

```javascript
.then(function(result) {
  console.log(result.done)
  console.log(result.value)
})
```

**Comment by jimmywarting** [comment]
it's know as [Object destructuring](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring) and can be done inside the the [function argument](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Pulling_fields_from_objects_passed_as_function_parameter)

**Comment by jimmywarting** [comment]
This is how i would write it if you want it do be in es5:

```javascript
$scope.file = streamSaver.createWriteStream("filename.txt");

fetch(url).then(function(res) {
    var reader = res.body.getReader();
    function pump() {
        return reader.read().then(function(result) {
            if (result.done) {
                return file.close();
            }
            return file.write(result.value).then(pump)
        });
    };

	pump($scope.file, reader);
	$scope.pump = pump;
});
```

**Comment by SetV** [comment]
Function `pump` will take argument that all the change I did. The mentioned ES5 changes are working. Thanks!
