### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by dudz94** [jimmywarting/StreamSaver.js#152]
Hey,

I'm working on a project which be able to download a large file (50Go+) using StreamSaver. 
First of all, thanks for your package and your time, it works perfectly.

I use the following example (a little bit remastered):  https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/saving-a-blob.html

I have a question about the download progress. How can I get the actual received size on my fetch request ? (in order to use a progress bar)
I made some tests, and I cannot get the dynamic size of fetch data.

Here it's my code. I hope you will find a solution.
`

            fetch(${BASE_URL}/api/XXXXXX, requestOptions)
                .then(res => {
                    const fileStream = streamSaver.createWriteStream(
                        this.state.name,
                        { size: res.headers.get('Content-Length') }
                    );
                    const readableStream = res.body

                    if (window.WritableStream && readableStream.pipeTo) {
                        return readableStream.pipeTo(fileStream)
                            .then(() => console.log('done writing'))
                            .catch(() => console.log("CATCH"))
                    }
                })`

Ask me if you need anything else !
Thanks ! Best,

**Comment by jimmywarting** [comment]
You can figure out how much you have downloaded, but not how much data have been saved (written). 

there are two answers to monitor fetch progress here using the reader.
https://stackoverflow.com/questions/35711724/upload-progress-indicators-for-fetch

but nobody mention a solution using pipeThrought so i also found this:
https://github.com/AnthumChris/fetch-progress-indicators/issues/8

Here is one of two possible solution:
```js
var loaded = 0
var size = +res.headers.get('Content-Length')

var progress = new TransformStream({
  transform(chunk, controller) {
    loaded += chunk.length;
    controller.enqueue(chunk);
  }
})

res.body
  .pipeThrough(progress)
  .pipeTo(fileStream)
  .then(success, fail)
```

---

fyi. there isn't any way to figure out how much you have uploaded to the server (yet), but you can almost certainly know that everything have been uploaded once you get the response header back (unless you are flushing something back as you are receiving data at the same time like a transformation stream or a pipe that just echo back everything - but it's unusual)
