### ISSUE TITLE
how to "append" the data into TXT

### ISSUE THREAD

**Issue by sexfio** [jimmywarting/StreamSaver.js#167]
If the "aaa.txt" already exists
how to "append" the new data into the "aaa.txt" ?
now it create a new TXT and the filename is aaa (1).txt ...

streamSaver.createWriteStream("aaa.txt", { flags: 'a+' });
I set mode 'a+', but it doesn't seem to work, please help me,I'm a beginner :)

**Comment by jimmywarting** [comment]
Think I mention to you at filesaver.js that they couldn't append data...?

It's true that StreamSaver can append data, but only to a newly downloaded/replaced file and as long as you have a WritableStream open... once it closes then you will have to downloaded/replaced the file again.

Basically you have to pre-append the file and then write all new data afterwards

```js
button.onclick = async () => {
    // Simulate a file you would normally get from `fileInput.files[0]`
    // or from some drag and drop or other means...
    const file = new File(['StreamSaver is awesome'], 'sample.txt')

    // Create a writableStream
    const writableStream = streamSaver.createWriteStream('sample.txt')

    // Pre append the previous part
    await file.stream().pipeTo(writableStream, {
      preventClose: true // don't close the writableStream when the file reading stream ends
    })
    
    // get a writer instance so you can write to it manually
    const writer = writableStream.getWriter()

    // append data into txt as long as you have more data to write
    writer.write(new TextEncoder().encode('..!'))

    // close it once you are done
    writer.close()
}
```

This will probably be the best you can do for your users at the moment.

You haven't been able to write to an existing file on the disk up until just recently, There is a new api called [native file system](https://github.com/WICG/native-file-system) but it's an ongoing trial right now. You can enable it in chrome but it will not work for all browser/client.
- you can enable a trail just for your domain: see [Origin Trials Guide for Web Developers](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md)
- or you can enable it in just your browser with experimental flags.

I have also developed an [adapter](https://github.com/jimmywarting/native-file-system-adapter) to that api, it works a bit like a shim/polyfill that can gracefully do some degree of fallback solutions.

if you want to help using "Native file system" then i can assist you with that also, or you can read up on this article: https://web.dev/native-file-system/ (note that some methods can be removed/deprecated - mainly around the part of chooseFileSystemEntries got changed to be split up two 3 different methods instead)

**Comment by jimmywarting** [comment]
PS, there is no flag option in StreamSaver, since it dose not have any read access. it mostly works like any other http download apart from that it works on the client side and it dose not close until you close the stream. so as long as it remain open then you can append data

**Comment by sexfio** [comment]
thank you very much :)
