### ISSUE TITLE
Pause stream when user pauses the download

### ISSUE THREAD

**Issue by jimmywarting** [jimmywarting/StreamSaver.js#17]
ReadableStream in the service worker keep pulling for more data even doe client paused the download. (The desiredSize is always 1)

This makes you think it's okey to keep pulling data from internet and piping it to the service worker while in fact it isn't

cc @yutakahirano

**Comment by yutakahirano** [comment]
Is it a Chromium bug? Could you file a bug in https://crbug.com/? Please cc yhirano@chromium.org.

Thanks,

**Comment by jimmywarting** [comment]
Done
https://bugs.chromium.org/p/chromium/issues/detail?id=642673

**Comment by yutakahirano** [comment]
Thank you!
