### ISSUE TITLE
Custom Service Worker

### ISSUE THREAD

**Issue by PaulTime** [jimmywarting/StreamSaver.js#170]
Hello, is it possible to use this lib if I already have my own custom service worker running?
I saw there is a way to change **streamSaver.mitm** property and host my own file, but I'm not sure that it's what I'm looking for, because I don't have any listeners in my sw, so it might be able replace the job of your hosted service worker

**Comment by jimmywarting** [comment]
You would kindof have to host mitm on your own domain and merge both service workers together

If you like you could also try my newer "native filesystem adapter". It works a bit different but it doesn't include a mitm and it's more a self hosted service worker solution. 

https://github.com/jimmywarting/native-file-system-adapter

**Comment by PaulTime** [comment]
ok, thanks
