### ISSUE TITLE
TS2540: Cannot assign to 'WritableStream' because it is a read-only property

### ISSUE THREAD

**Issue by bt-88** [jimmywarting/StreamSaver.js#174]
We want to ponyfill `streamSaver.WritableStream` with `web-streams-polyfill/ponyfill` in our React application (`16.8`) with TypeScript (`3.5.3`) as follows:

```
import * as streamSaver from "streamsaver";
import { WritableStream, TransformStream } from "web-streams-polyfill/ponyfill";

function handleResponse(res: Response) {
   if (!streamSaver.WritableStream) {
        // Link pony fill
        streamSaver.WritableStream = WritableStream;
   }

   // Etcetera
}
```

TypeScript tells us `TS2540: Cannot assign to 'WritableStream' because it is a read-only property.`. What are we doing wrong here?

**Edit**

I learned that a namespace import is read-only: you cannot change its properties.

When we change it to `import streamSaver from ...` it tells me that `@types/streamsaver` doesn't contain a default export.

Indeed, the type contains createStreamWriter, WritableStream, ReadableStream, etcetera.

Can anybody point us in the right direction? Thanks a ton.

**Comment by jimmywarting** [comment]
I'm no expert at typescript as i don't use it myself...

probably would have done it this way doe:

```js
import * as streamSaver from 'streamsaver'

const { WritableStream, TransformStream } = streamSaver
streamSaver.WritableStream = WritableStream
```

**Comment by bt-88** [comment]
> I'm no expert at typescript as i don't use it myself...
> 
> probably would have done it this way doe:
> 
> ```js
> import * as streamSaver from 'streamsaver'
> 
> const { WritableStream, TransformStream } = streamSaver
> streamSaver.WritableStream = WritableStream
> ```

Ah, yes indeed. The trick is to deconstruct the `streamSaver` namespace like this:

```
let { WritableStream, TransformStream } = streamSaver;
```

Now WritableStream is not read-only.

**Comment by bt-88** [comment]
@jimmywarting :

What is the suggested way to apply the ponyfill?

Should we check if `window.WritableStream` is undefined or `streamSaver.WritableStream` (or doesn't it matter)?

Thanks again.

**Comment by jimmywarting** [comment]
```js
import * as streamSaver from "streamsaver";
import * as ponyfill from "web-streams-polyfill/ponyfill";

streamSaver.WritableStream = streamSaver.WritableStream || ponyfill.WritableStream;
```
you don't have to do anything to TransformStream
