### ISSUE TITLE
StreamSaver.js does'nt work

### ISSUE THREAD

**Issue by wangmengqin** [jimmywarting/StreamSaver.js#175]
https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=2.0.0   cannot access

![image](https://user-images.githubusercontent.com/34430252/89113582-8a1bee00-d4a5-11ea-9934-3920d0b817c5.png)

**Comment by jimmywarting** [comment]
Seems like you have something that's blocking it?
I can access it just fine

**Comment by niccololampa** [comment]
@jimmywarting Can I ask why access to this url is needed for download to execute? What if app will work only within an internal network that doesn't have external internet access?

**Comment by jimmywarting** [comment]
1 main cause: it won't work without a service worker.

first reason: insecure sites don't have access to service worker (power feature stuff) so the only other way was to transfer a messageChannel from http -> https -> service worker

2nd reason: i wanted to make it easier for everyone else to not have to deal with the service worker installation setup.
i wanted it to just be as easy as requiring the main streamsaver.js from npm or jsfiddle and just have it working

**Comment by niccololampa** [comment]
@jimmywarting Thank you for the quick reply. 🏄‍♂️ . Guess I have to find a way to make it work. 😄 

Awesome work on this package. 💯
