### ISSUE TITLE
When opened in IE 11, the whole website doesnt load cause of Syntax Error

### ISSUE THREAD

**Issue by jahusa02** [jimmywarting/StreamSaver.js#176]
Hey,

I have an Angular app which works fine on Firefox and Chrome but when I open it in IE11, the console throws an Sytax Error right on this part

![grafik](https://user-images.githubusercontent.com/33373041/89260143-fa547c00-d62b-11ea-907f-555da0b26182.png)

Your examples wont work in IE, but i would use a fallback for this. I just want the app to be loaded in IE11

**Comment by jimmywarting** [comment]
umh, not sure if i want to support IE. it's not just the try catch, it's all arrow function all over the place.

Have you considered not supporting IE? it's pretty much on its last breath now.
Otherwise have you considered code splitting and not load streamsaver if it's IE?
streamsaver don't work anyway in IE, since it don't have service worker. so it would be better to just use blob and `<a download href>` directly

**Comment by jahusa02** [comment]
Sadly I have to support it.

When I import streamsaver dynamically, I can't assign the Ponyfill. 
Firefox always complains with
`TypeError: setting getter-only property "WritableStream"`

Here is my code: 

```
import(/* webpackChunkName: "streamsaver" */'streamsaver').then(streamSaver => {
        import(/* webpackChunkName: "web-streams-polyfill" */'web-streams-polyfill/ponyfill/es6').then(ponyfill=> {
          if (!window.WritableStream) {
            streamSaver.WritableStream = ponyfill.WritableStream; // --> Throws error
          }
          fetch(url, {
            method: 'POST', body: form, headers: {
              'Accept': '*/*',
              'Origin': this.stashcatService.baseUrl
            }
          }).then(res => {
            const fileStream = streamSaver.createWriteStream(file.name);
            console.log(res);
            const readableStream = res.body;

            if (window.WritableStream && readableStream.pipeTo) {
              return readableStream.pipeTo(fileStream)
                .then(() => console.log('done writing'));
            }

            window.writer = fileStream.getWriter();

            const reader = res.body.getReader();
            const pump = () => reader.read()
              .then(res2 => res2.done
                ? window.writer.close()
                : window.writer.write(res2.value).then(pump));

            pump();
          });
        });

      });
```

**Comment by jahusa02** [comment]
Sadly I have to support IE11... 

I dynamically import Streamsaver now. Thanks for the hint!
