### ISSUE TITLE
WebRTC Data channel support

### ISSUE THREAD

**Issue by PopTudor** [jimmywarting/StreamSaver.js#180]
Hello, thank you for your efforts and I want to say that the library is great!

I have however an issue that I'm hoping you might help me. Nothing fancy.
I send through WebRTC data channel some chunks read through FileReader and I want to write the chunks to StreamSaver, kind of like WebTorrent but I hope to bypass the memory issue that they have since they need to keep everything in memory to make it able to work as a torrent (hash each chunk & serve chunks from memory when other request it). 
I don't need that for the web so I want to send the files as they are read from peer A and save it to peer B.
```javascript
dataChannel!.onmessage = (event: MessageEvent) => {
	await window.writer.write(event.data);
	totalReceived += event.data.byteLength;
	if (totalReceived === 93185) {
		console.log('end reading file')
		await window.writer.close()
	}
}
```
is pretty straight forward: write to StreamSaver (global instance), increment the counter and close the writer when we received the total file size (hardcoded in the example above). If the file is small enough, works fine since is doing 1 single read/write...when is doing multiple reads/writes it never saves the file on my machine although I get everything. Any idea what could be? spent like 2-3 days on this and can't figure it out...I will keep pursue it until I find something

**Comment by PopTudor** [comment]
it seems that does not work because event.data is ArrayBuffer but write must be passed uint8array in order to work properly.

**Comment by jimmywarting** [comment]
Yepp, StreamSaver only accepts Uint8Array as that is the only thing a streaming response accepts. the rule comes from a higher order from service workers:

```js
evt.respondWtih(
  new Response(
    new ReadableStream({
      start(ctrl) {
        ctrl.enqueue(new Uint8Array([97])) // works
        ctrl.enqueue(new ArrayBuffer(1)) // breaks
      }
    })
  )
)
```

The stream spec says something like: it can either be a byte stream or a stream of objects
for it to be a byte stream you can only emit Uint8Array's for it to be able to work with thinks like the BYOB reader

![image](https://user-images.githubusercontent.com/1148376/94347888-753c8080-0038-11eb-901b-fad3828b1d2e.png)

I could add a transformation pipeline to also handle other types like arraybuffer, strings blobs etc but that would just increase the bundle. will instead just let it be up to the developer to handle

**Comment by PopTudor** [comment]
Thanks for these doc!  I was not aware of them.. indeed some explicit mention in the README would be helpful as mentioned in issue #181 will follow that topic. Thanks again!
