### ISSUE TITLE
Feature request: Set MIME type?

### ISSUE THREAD

**Issue by mcclure** [jimmywarting/StreamSaver.js#182]
I've been experimenting with a test, based on [this example](https://jimmywarting.github.io/StreamSaver.js/examples/saving-a-blob.html), running on localhost with http-server from npm, testing in Chrome on OS X.

It works, and that's neat! But **every** time, both when it works, and when I get the silent failure I describe in #181, it prints this weird message to 

> StreamSaver.js:49 Resource interpreted as Document but transferred with MIME type application/octet-stream: "https://jimmywarting.github.io/StreamSaver.js/127.0.0.1:8080/315353/mcc.mta".

mcc.mta is the correct name of the file I'm downloading. I assume the rest of the URL is something to do with your mitm trick.

But the MIME warning is interesting to me. It makes me wonder two things:
1. Is the warning concerning?
2. Regardless of what the warning means: What if I wanted a particular MIME type other than `application/octet-stream`? At a certain point I might want to use, for example, `application/cbor`.

Would it be difficult to add a feature where we could specify custom MIME types?

**Comment by jimmywarting** [comment]
`Resource interpreted as Document but transferred with MIME type application/octet-stream:` is nothing more than a warning/info. 
Browsers fallback behavior is to download the resource if it's unable to render the content on the page. Which is what we want. 

If it would be say like text/plain or `application/pdf` then the result would be rendered in a hidden iframe and not be downloaded. even worse if the type was set to text/html then the file would not be download. it would render everything and also run any script code inside of it.

so to answer your question: No, it's not something you should be concern about.

**Comment by mcclure** [comment]
That makes sense, thanks. You can close this issue if you want
