### ISSUE TITLE
Youtube Video download fails with CORS message

### ISSUE THREAD

**Issue by promotion** [jimmywarting/StreamSaver.js#187]
Hi, 

when im trying to download the Youtube Video via the working generated direct link  (generated with youtube-dl lib , and download from browser if entered directly) . Example of link below , but it can expire soon.

However whn trying to implement it using https://jimmywarting.github.io/StreamSaver.js/examples/fetch.html exmplae , i would get responce:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://r3---sn-a5mekn7y.googlevideo.com/videoplayback?expire=1602372089&ei=me2BX_TOIJyY2_gPhIWz6A0&ip=192.241.94.91&id=o-AH_88qkUebTTVyePwgSxz6NEqLx5HajrHqy9yWKDNSJO&itag=18&source=youtube&requiressl=yes&mh=Vm&mm=31%2C29&mn=sn-a5mekn7y%2Csn-a5mlrn7l&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=676250&vprv=1&mime=video%2Fmp4&ns=LH_UrMywNbQZO-g9U1f5yRcF&gir=yes&clen=11913650&ratebypass=yes&dur=136.115&lmt=1581409363006844&mt=1602350351&fvip=3&fexp=23915654&c=WEB&txp=5531432&n=HGHhMdJb-8lfAamYV&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOIhSLUZ2QPM7bFp1eqVoLC8Wmbi89_X8AwwX7c3ZfHNAiEA6ta3JlU51-V9QVkU1qV3F8rrF0F0N_j3SXCZdIJhAOs%3D&sig=AOq0QJ8wRgIhAJ7oeAZUoReTW9iHZX_EHudjytZDifYUExKnD_DWDdqMAiEA4yMmaYccxGrliPsZ6nuRjFyOD_kamEnwET3JV0w-7Os=. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Could you let me know if this could be solved somehow ? 

LINK ITSELF :
https://r3---sn-a5mekn7y.googlevideo.com/videoplayback?expire=1602372089&ei=me2BX_TOIJyY2_gPhIWz6A0&ip=192.241.94.91&id=o-AH_88qkUebTTVyePwgSxz6NEqLx5HajrHqy9yWKDNSJO&itag=18&source=youtube&requiressl=yes&mh=Vm&mm=31%2C29&mn=sn-a5mekn7y%2Csn-a5mlrn7l&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=676250&vprv=1&mime=video%2Fmp4&ns=LH_UrMywNbQZO-g9U1f5yRcF&gir=yes&clen=11913650&ratebypass=yes&dur=136.115&lmt=1581409363006844&mt=1602350351&fvip=3&fexp=23915654&c=WEB&txp=5531432&n=HGHhMdJb-8lfAamYV&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAOIhSLUZ2QPM7bFp1eqVoLC8Wmbi89_X8AwwX7c3ZfHNAiEA6ta3JlU51-V9QVkU1qV3F8rrF0F0N_j3SXCZdIJhAOs%3D&sig=AOq0QJ8wRgIhAJ7oeAZUoReTW9iHZX_EHudjytZDifYUExKnD_DWDdqMAiEA4yMmaYccxGrliPsZ6nuRjFyOD_kamEnwET3JV0w-7Os=

Thanks

**Comment by jimmywarting** [comment]
Well, the problem isn't with streamsaver, its with [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
