### ISSUE TITLE
Download url showing as github.io

### ISSUE THREAD

**Issue by hashitha** [jimmywarting/StreamSaver.js#19]
When downloading chrome shows that the download is coming from 

`https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.5528359912470291`

Is there a way we can change this behaviour. I am running from https with a valid certificate.

![capture](https://cloud.githubusercontent.com/assets/10569142/18193501/c7a22e80-7110-11e6-9f34-d4bfde6c5e8b.PNG)

**Comment by jimmywarting** [comment]
I have been thinking of a way to configure where the service worker comes from, So github.io is not involved but also keep it simple enough for developers to set it up themselves.

I chosed github.io as default b/c since 
- it easier to use
- So http site can use it as well
- And also so it doesn't conflict with any other service worker
- and have no problem with the url scopes.

The URL configuration could be easy enough to just change the url.
But if the site is using using https should we then remove the mitm.html? It can still maybe be useful since it it's more flexible with scopes

**Comment by jimmywarting** [comment]
I have also though about adding a reference parameter to the url so files can be re-downloaded if it fails and you would like to try again. But then I need to redirect back to the site in two ways. With the service worker and with one without if it's not installed

**Comment by hashitha** [comment]
I think it may be better to remove mitm.html for https and don't think re-download if it fails is needed because the user can click the same button again to download.

**Comment by jimmywarting** [comment]
It's not just about clicking the same button again b/c you are not on the same page... When I aborted the download I will see this in my download history
![skarmavbild 2016-09-02 kl 11 24 01](https://cloud.githubusercontent.com/assets/1148376/18199274/db25188e-70ff-11e6-8511-dace579f0a1f.png)
The "TRY AGAIN" button don't work... hence why i want a referer parameter in the url to fallback to. I think this is a separate issue all together...

**Comment by hashitha** [comment]
You are right; it 'd be nice if try again works, not sure if it will work in our case though because we download multiple files and then write the zip to the stream. Might be better to create a separate issue for this. 

More important is that the download URL shows as coming from the same domain. I had a user ask me if it is downloading a virus as he didn't know what that URL was.

**Comment by jimmywarting** [comment]
I think we first have to understand what issues removing the mitm.html can bring to the scope - I have dealt with it before and it's quite a nasty thing to work around

> Only one service worker per scope is allowed to be registered so the latest kick the previous one out unless the scope is more specific, in this case, the request is attended by the most specific only.

So you have a problem that you can only have one SW at the time so do you 
A) ImportScript if you already have a SW of your own or:
B) Be more specific about the scopes? 

The mitm.html isn't that bad actually it lets you be more flexible with the scope, you can put it away in the harms way of any other SW that you might already have
so the service worker can be installed and used from:

`https://example.com/js/lib/streamsaver/mitm.html`
`https://example.com/js/lib/streamsaver/sw.html`

Then you can avoid issues when trying to install the service worker and download a file from `https://example.com/download/:file-id`

It would be nice to avoid conflicts like this:
> Registration failed with SecurityError: Failed to register a ServiceWorker: The path of the provided scope ('/practice/foopage/') is not under the max scope allowed ('/static/mod/practice/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope. - [Stackoverflow](http://stackoverflow.com/questions/35780397/understanding-service-worker-scope)

Worth reading the stackoverflow

**Comment by jimmywarting** [comment]
Essentially it comes down to the developers own preference of where he would like to put the SW and under witch scope. This is without my control - and I'm unsure what to do ATM 

Do I keep the mitm?
How do you use a custom url if the answer is yes?
```javascript
streamSaver.mitm = 'http://example.com/streamsaver.js/mitm.html'
```
If not - how can I help sending a messageChannel to the correct SW that a developer has hosted himself?
And can it be used from all kinds of url sub-paths?

That is some question i have been asking myself

**Comment by hashitha** [comment]
In that case, why don't you have it as you suggested?

keep the mitm and have it in 

```
https://example.com/js/lib/streamsaver/mitm.html
https://example.com/js/lib/streamsaver/sw.html
```

or let the developer configure the path

**Comment by jimmywarting** [comment]
@eligrey can i get your opinion on this? do you have any thing to say about this?

**Comment by jimmywarting** [comment]
now you can at least do:

streamsaver = require('streamsaver')
streamsaver.mitm = 'xxx'

**Comment by asko123** [comment]
Hi 
I recently started using stream saver. But for some reason when ever I trigger the download button that invokes the  streamSaver createWriteStream method the redirect to https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.6630165085230095  which gives me a 404. I am not sure if I am missing some configuration. The image below show the response I get
I also add the mitm.html view-source:https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0 but not sure where in the stream saver to update its location 
If you could give me any tip would be great
Thanks
![image](https://cloud.githubusercontent.com/assets/6355869/22344354/8091f33a-e3c1-11e6-9295-93ae464d655f.png)

**Comment by asko123** [comment]
I think changing on the script streamSaver.mitm = 'https://localhost:9000/StreamSaver.js/mitm.html?version=' +
		streamSaver.version.full

fixed it

**Comment by enriquemorenotent** [comment]
None of these solutions are working for me. Changing the `.mitm` breaks completely my download.

**Comment by jimmywarting** [comment]
are you serving your mitm.html/sw.js file from a secure origin like https or localhost?

**Comment by enriquemorenotent** [comment]
No, it is normal http

**Comment by jimmywarting** [comment]
you can't install a service worker on normal http sites... You can only install service worker on secure sites such as https and localhost read this for more information: https://goo.gl/Y0ZkNV

**Comment by coffeenexus** [comment]
This is not working for me either, all the downloads in my download tab look like this   
But I'm using React with streamsaver: 1.2.0

![image](https://user-images.githubusercontent.com/15251286/55282235-2a8c5c00-530e-11e9-9d9c-accd6f318515.png)

**Comment by jimmywarting** [comment]
if you want to change the domain to your own you would need to host the service worker yourself also (in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)). 

```js
import streamsaver from 'streamsaver';
streamsaver.mitm = myOwnMITM
const { createWriteStream } = streamsaver
```
