### ISSUE TITLE
"document is not defined" error with vue + nuxt

### ISSUE THREAD

**Issue by tom-rt** [jimmywarting/StreamSaver.js#192]
Hello,

I have a front end using Vue and Nuxt.
When I try to load/refresh the page where I import streamSaver as such:

`import streamSaver from "streamsaver";`

I systematically get the following error:

![Screenshot from 2020-11-25 15-41-47](https://user-images.githubusercontent.com/15687145/100243428-26c33980-2f36-11eb-828d-17585851bcd0.png)

And a warning message appears in my console: 

![Screenshot from 2020-11-25 15-49-26](https://user-images.githubusercontent.com/15687145/100243492-38a4dc80-2f36-11eb-945e-47ddf44a6f6c.png)

I tried with chrome and firefox on linux and installed streamsaver via `npm install streamsaver`
I use node v14.15.1

Thanks very much in advance for your answer.

**Comment by jimmywarting** [comment]
whenever you use Nuxt you renderer all things on the server side using node
node don't have document, window or location... 

You should use it on the client only - ont the server https://nuxtjs.org/examples/plugins-client-only

> `plugins/client-only.client.js` uses the `window.alert()` function which is not available on server side.
>
> `nuxt.config.js` contains the plugins property which registers the plugin on the client side by adding the `.client` extension.


```js
export default () => {
  import streamSaver from "streamsaver"
  window.alert('I work only on client side')
}
```

**Comment by tom-rt** [comment]
Sorry about that, thanks for your work and your answer !
