### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by DannyZB** [jimmywarting/StreamSaver.js#2]
You were a bit unclear on what the SSL issues are.

I tried running the example from my server over HTTP/2 + SSL and it gave an error :+1: Mixed Content: The page at '*secret*' was loaded over HTTPS, but requested an insecure resource 'http://localhost:3000/'. This request has been blocked; the content must be served over HTTPS.

Is there any way around that or is the solution wrong for HTTPS?

p.s. I'm looking into implementing this into Seedr.cc, a lot of users would benefit from this!

**Comment by jimmywarting** [comment]
Beware, the syntax/api will change later. And it doesn't work in any browser (apart from chrome with a flag) will be enabled in 52

But here is the deal. 
- It requires service worker to work...
- Service worker are very strict about certificate and don't like self generated certificate either (don't like untrusted so it throws a error)
- But localhost and 127.0.0.1 is whitelisted on http
- and http2 don't work on http...

So i guess there is a conflict here... not sure 

But i believe there is a solution out there. Maybe changing `http://localhost:3000/` to `//localhost:3000/`would be a start

**Comment by DannyZB** [comment]
GET https://localhost:3000/ net::ERR_CONNECTION_REFUSED

Not so surprising ... localhost has no certificate attached.
P.S. I am running this from a server with a proper certificate.

Sounds like the technology is in it's infancy

**Comment by jimmywarting** [comment]
Hi, I have found a hack to use service worker on `http://` and `file://` protocols as well

Also the script (StreamSaver.js) are now using a "man in the middle" from github pages that will hopefully remove all the hassle of setting up a service worker and handle stuff like certificate and not come in conflict with the owners website where only one service worker can run at the time

My first goal was to make this work on both http and https so everyone can use this, it had it's dark moments where i thought it would not be possible but it was. 
So everything have been built around this "Man in the middle" (that lives on github-pages) to hopefully make it easier for people to start using StreamSaver.js

Also planing on building a local version where you don't need to depend on the "mitm" from github pages and where you are using your own certificate and your own service worker

This should just work fine with both https/2 i think

**Comment by jimmywarting** [comment]
Hi, by just using StreamSaver.js would you be able to pull it of now as it is?
