### ISSUE TITLE
Can't set up streamSaver.mitm when using an async import

### ISSUE THREAD

**Issue by Owpac** [jimmywarting/StreamSaver.js#211]
Hello,

First of all, thank you for your work.

I tried to define my own service worker with streamSaver.mitm = 'url' and with Object.defineProperty but none of them worked since I import Stream Saver in async (because I'm using SSR for my website):

```js
const streamSaver = await import('streamsaver')
...
streamSaver.mitm = ${getBaseUrl()}/stream-saver/mitm.html
```

![image](https://user-images.githubusercontent.com/29702840/111288132-3204b700-8644-11eb-9a21-e9469de5cdcb.png)

One solution that should work is to set up mitm with global variables like for WebStreamsPolyfill:
```js
const ponyfill = global.WebStreamsPolyfill || {}
...
WritableStream: global.WritableStream || ponyfill.WritableStream,
```

```js
const mitmUrl = global.MitmUrl || {}
...
mitm: mitmUrl || 'https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=2.0.0'
```

**Comment by jimmywarting** [comment]
I think you have to do:
```js
const {default as streamSaver} = await import('streamsaver')
```

**Comment by Owpac** [comment]
Ok you are right, it's working with:

```js
const {default: streamSaver} = await import('streamsaver')
```

Thanks a lot.

**Comment by jimmywarting** [comment]
ups, was mixing import and destructing re-assignments
Glad it worked out for ya
