### ISSUE TITLE
[question] README clarification

### ISSUE THREAD

**Issue by redbrain** [jimmywarting/StreamSaver.js#222]
From the explanation portion of README.md:
> 2. Transfer the stream (or DataChannel) over to the service worker using postMessage.

What is a DataChannel? Is it something I should know about when writing a web app with StreamSaver?

Thank you!

**Comment by jimmywarting** [comment]
> What is a DataChannel? 

a DataChannel or rather a [MessageChannel](https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel) as it's actually called is a way of transferring data through two MessagePort via postMessages. similar to window.postMessage but more private

> Is it something I should know about when writing a web app with StreamSaver?

Nope 🙂 
just a explanation 

[ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) and [WritableStreams](https://developer.mozilla.org/en-US/docs/Web/API/WritableStream) is what you need to learn if you know how it works then you basically knows the in and outs of how StreamSaver 

There isn't much you have to learn about StreamSaver, just that it creates a download stream in some magical way throught service worker.
All you need to know is how to pipe/write data to from one stream into another. StreamSaver only has one method which is the `createWriteStream()` that returns a WritableStream and that is the only thing you have to work with
