### ISSUE TITLE
Javascript - Abort a download 

### ISSUE THREAD

**Issue by jimmywarting** [jimmywarting/StreamSaver.js#23]
The Response constructor only accepts a ReadableStream atm, but a WritableStream will come eventually (I hope). Until then I'm trying to map a `getWriter().abort()` function to call `ReadableStream.cancel()` But that is not possible
```
TypeError: Cannot cancel a readable stream that is locked to a reader(…)
```
So I try to cancel the last thing it was locked to... The Response constructor. 
`res.body.cancel()`
But that is also locked to a reader. A reader out of my control

So I'm going with my last resort which is to make the readableStream to a errored state
https://github.com/jimmywarting/StreamSaver.js/commit/1108a2c36b92b0fac231302c459b982b466261ce, https://github.com/jimmywarting/StreamSaver.js/commit/f60b23e33dc0dde493d2222a7ac041e7b517fb99

It doesn't seem right to me to call error when the there was no error. It has only been aborted/canceled

But even after making the readable stream state a errored state it still looks like chrome is downloading the file.
I don't know if it's a bug in chrome/streams/fetch or if I'm doing something incorrect. Or isn't this going to be possible until the Response constructor can accept a writableStream as body?

Maybe a friendly ping to @domenic can help me

**Comment by domenic** [comment]
I don't have the full context on this repository, so let me try to respond to the points I understand and ask for clarification otherwise...

> The Response constructor only accepts a ReadableStream atm, but a WritableStream will come eventually (I hope).

If you mean that WritableStream will eventually be implemented, yes. But there are no plans to integrate it into Response or the Response constructor. You'll be able to do something like

```js
const { readable, writable } = TransformStream.identity();
new Response(readable);
writable.getWriter().write(...);
```

if you want.

> So I'm going with my last resort which is to make the readableStream to a errored state
1108a2c, f60b23e

If you are erroring the readable stream, then presumably you created it. In that case you can close it instead of just erroring. Close is basically equivalent to canceling here, i.e. cancel is just "close from the outside, and call the underlying source's cancel()".

> But even after making the readable stream state a errored state it still looks like chrome is downloading the file.

This does sound like a bug, although I think @yutakahirano fixed a related one recently. Maybe the same one? https://bugs.chromium.org/p/chromium/issues/detail?id=627046

A small repro would probably help.

**Comment by jimmywarting** [comment]
> TransformStream.identity();

Neat trick 👍 

> If you are erroring the readable stream, then presumably you created it. 

Yes

> In that case you can close it instead of just erroring. Close is basically equivalent to canceling here, i.e. cancel is just "close from the outside, and call the underlying source's cancel()".

If "Close is basically equivalent to canceling" then I thought about it all wrong. cuz when i call `controller.close()` then the download is completed - Like: All done!
Thought cancel would abort the download...


That chrome bug looks related

**Comment by domenic** [comment]
Ah, yeah, to abort the download I think you'd want to error, signaling that this download is not succesful. Although even then I imagine many browsers will let users keep the partially-downloaded file... I think I've seen that happen before on spotty wifi with Chrome, at least.

**Comment by jimmywarting** [comment]
It was just that the writableStream had 2 events `close & abort` and i thought i could use them in some neat way...

```javascript
WritableStream({
	close() {
		console.log('All done!')
	},
	abort(e) {
		console.log('Abort the download!')
	}
})
```

Guess i have to go with signaling a error if it isn't going to be possible

**Comment by domenic** [comment]
Well no, I think you *were* on the right track there. If you do the identity transform trick, calling `ws.getWriter().abort()` will cause the readable stream to error (not just close). It makes sense: if the person producing data says "abort with this error", then anyone reading the data should see "the stream has errored with this reason; I can't get any more data".

**Comment by jimmywarting** [comment]
Ok, It's all clear now. Thanks for your explanation on streams!
Then everything I have done is already complete. Just need to wait for that chrome bug.

**Comment by domenic** [comment]
That particular one should be fixed in Canary, so it'd be worth testing there, and if it isn't then maybe raising a new bug :)

**Comment by jimmywarting** [comment]
My StreamSaver [example](https://jimmywarting.github.io/StreamSaver.js/example.html) don't even work on Canary. So i couldn't test that.

The page gets redirected to intercept-me-nr0.264 like if the fetchEvent handler didn't even get registered. But it works in Chrome stable...

**Comment by domenic** [comment]
Dang, that sounds like a good bug to file by itself...

**Comment by yutakahirano** [comment]
I chatted with my colleagues developing SW in Chrome. They said event handlers need to be registered when the service worker script is evaluated (see step 15 in https://w3c.github.io/ServiceWorker/spec/service_worker/index.html#run-service-worker-algorithm). Is that the problem?

**Comment by nhiroki** [comment]
(And see also step 15 in https://w3c.github.io/ServiceWorker/spec/service_worker/index.html#on-fetch-request-algorithm)

> To avoid unnecessary delays, the Handle Fetch enforces early return when no event listeners have been deterministically added in the service worker’s global during the very first script execution.

**Comment by jimmywarting** [comment]
> They said event handlers need to be registered when the service worker script is evaluated

Dang! I'm just lucky to found out about this before it hits stable. Don't think it will be a problem.

**Comment by jimmywarting** [comment]
Woho, some SW refactoring and bala bing bala bong! My example works!
putting the file in a errored state works to 👍
