### ISSUE TITLE
self host mitm.html

### ISSUE THREAD

**Issue by crapthings** [jimmywarting/StreamSaver.js#231]
https://github.com/jimmywarting/StreamSaver.js/blob/master/StreamSaver.js#L31

mitm: 'https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=2.0.0'

```js
const fileStream = streamSaver.createWriteStream(`${filename}.zip`, {
  size: _.sumBy(downloads, 'length'), // optional downloading progress
  mitm: `${protocol}//cube-public.oss-cn-beijing.aliyuncs.com/cube-cdn/public/mitm.v2.0.0.html`,
});
```

**Comment by JamesCorrigan** [comment]
I'm having the same problem. are you using react?

**Comment by jimmywarting** [comment]
the protocol can never be anything else other than https b/c service worker is a power feature and requires the site to be secure (https), so you could as well hardcode the protocol to https also

only time it works with http is if the site is localhost or explicit whitelisted

**Comment by guest271314** [comment]
> only time it works with http is if the site is localhost or explicit whitelisted

mitm.html can be used from a minimal Chrome extension by specifying `"web_accessible_resources"` in manifest.json.

**Comment by jimmywarting** [comment]
Oh, right one more thing that is not how you are suppose to configure the mitm within createWriteStream option...
you only do it once

```js
import streamSaver from 'streamsaver'
streamSaver.mitm = 'https://cube-public.oss-cn-beijing.aliyuncs.com/cube-cdn/public/mitm.v2.0.0.html'
```
