### ISSUE TITLE
Downloads don't work on the first attempt

### ISSUE THREAD

**Issue by JamesCorrigan** [jimmywarting/StreamSaver.js#235]
I have the service worker hosted in a react app and the download function is working, but it doesn't work on the first attempt because the service worker is not registered yet. I need to register the service worker before my download function is called, but so far I have been unable to do that. Is there a way to ping streamsaver with an empty message so that the serviceworker gets registered before downloads happen?

**Comment by jimmywarting** [comment]
dupl #233
