### ISSUE TITLE
Cannot set mitm when working in typescript using a type definition

### ISSUE THREAD

**Issue by jhnguyen521** [jimmywarting/StreamSaver.js#244]
import * as streamSaver from "streamsaver";
streamSaver.mitm = "url"

will give an error
Cannot assign to 'mitm' because it is a read-only property.

**Comment by jhnguyen521** [comment]
PR for potential fix
https://github.com/jimmywarting/StreamSaver.js/pull/243

**Comment by JounQin** [comment]
I'm using `Object.assign(streamSaver, {})` for workaround.
