### ISSUE TITLE
Use GitHub Releases

### ISSUE THREAD

**Issue by lewisgoddard** [jimmywarting/StreamSaver.js#26]
Pertaining to https://github.com/jsdelivr/jsdelivr/pull/13597#issuecomment-246011017 I would like this in a CDN. JSDelivr auto-updates, but they rely on Git releases to do it. Would you be able to utilise Git releases at some point?

I saw you comment somewhere that this wasn't stable, and it's clearly actively developed, but I would love to see this released as I require it to implement WebTorrent.

**Comment by jimmywarting** [comment]
That was awhile ago. It's stable now. In fact - I plan to publish it to npm as 1.0.0 before I go to bed
From hero on out it will only be improvements and bug fixes. The API is solid

**Comment by jimmywarting** [comment]
But yea I can use GitHub releases so it will work with bower also

**Comment by lewisgoddard** [comment]
That would be awesome. JSDelivr use their own bot to pull in releases straight from GitHub, but it just needs it to be tagged on GitHub.

**Comment by jimmywarting** [comment]
Fixed
