### ISSUE TITLE
Download chunks and combine 

### ISSUE THREAD

**Issue by NumairAwan** [jimmywarting/StreamSaver.js#268]
How can i download multiples files (chunks) stored in my server and combined them into one file and then download? any example? 

For example: 

I have 10 chunks file of 1 file that is test.zip and file size is 100mb. So each chunk size is 10mb.

**Comment by jimmywarting** [comment]
why is your archive splited up in multiple chunks?
anyhow. i would recommend you to keep using the server if possible to save the zip instead of emulating a server using streamsaver.js and a service workers

but if you insist on using streamsaver anyway then you would have to make something like:

```js

const chunks = [
    'https://example.com/',
    'https://example.com/',
]

function concatenateRequests(requests) {
    const ts = new TransformStream()
    const pump = () => {
        const it = requests.next()
        if (it.done) return ts.writable.close();
        fetch(it.value).then(res => {
            console.log(res.body);
            return res.body.pipeTo(ts.writable, { preventClose: true })
        }).then(pump, ts.writable.abort.bind(ts.writable));
    }
  
    pump();
  
    return ts.readable;
  }

  concatenateRequests(chunks.values()).pipeTo(streamSaver.createWritableStream('archive.zip'))
```

**Comment by NumairAwan** [comment]
Thanks for the example but i am getting "Uncaught ReferenceError: TransformStream is not defined" in firefox and in chrome i am getting "Uncaught TypeError: streamSaver.createWritableStream is not a function". I change streamSaver.createWritableStream to streamSaver.createWriteStream and now its working fine in chrome but the firefox error is still there.

**Comment by NumairAwan** [comment]
Also download is working in brave browser but getting some errors in console log

![image](https://user-images.githubusercontent.com/62851858/155666208-405ccdbb-b520-4e61-b638-7296321efe18.png)


note: i am hosting the custom sw.js and mitm.html
