### ISSUE TITLE
Has it improved in Safari 15.4?

### ISSUE THREAD

**Issue by ogawa0071** [jimmywarting/StreamSaver.js#272]
> There’s also new support for allowing users to download files generated by a ServiceWorker.
https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/

Safari 15.4 release notes mention the handling of files in ServiceWorker.

Until now, I think that Safari could not process files that were larger than the amount of memory and were divided.

Will it be improved in Safari 15.4?

**Comment by jimmywarting** [comment]
Grate news, have a Mac, so going to test it out later today if it works... (locking/moving) this to an already existing issue, where more ppl are already subscribed.
