### ISSUE TITLE
Firefox download stops after 30 seconds

### ISSUE THREAD

**Issue by eoc-ross** [jimmywarting/StreamSaver.js#290]
Hi, I'm using estensiveliy StreamSaver to download large zip files (1Gb+). It appears to work fine with Chrome and Safari, but I'm having some issue with Firefox which always abort (mostly silently) the download after 30 second.

I also tried to throttle the download down to 1mb/sec, nothing changes: the download always stops after 30 seconds.

System info:
 - Ubuntu 22.04 - 16gb ram / 8 core - firefox 104 - https remote host and http localhost
 - Windows 10 - 32gb ram / 16 core - firefox 104 - https remote host

Anyone experiening the same issue?

**Comment by eoc-ross** [comment]
Turns out that was a problem with version 2.0.2 of web-stream-polyfill. Upgrading to 3.2.1 solved the issue.

**Comment by davidpan123** [comment]
https://github.com/jimmywarting/StreamSaver.js/issues/292

**Comment by davidpan123** [comment]
The problem persists after the upgrade to 3.2.1.

**Comment by jeremyckahn** [comment]
Can this issue be reopened? I'm experiencing it consistently on Firefox 110.

**Comment by elliotsayes** [comment]
Also experiencing problems here! Anyone had any luck with workarounds/alternatives?

**Comment by jeremyckahn** [comment]
It seems that https://github.com/jimmywarting/StreamSaver.js/pull/305 should fix this issue.
