### ISSUE TITLE
Streamwriter is slow under Chrome/Chromium browser

### ISSUE THREAD

**Issue by morula** [jimmywarting/StreamSaver.js#303]
Compared to Firefox, writing a large file under Chrome is about 30 times slower (Firefox 992KB/s, Chrome 38.4KB/s).

I can also reproduce a similar result with the StreamerSave example "https://jimmywarting.github.io/StreamSaver.js/examples/torrent.html".

```
const writeStream = createWriteStream('test.zip');
const writer = writeStream.getWriter();

jszip
  .generateInternalStream({type: "blob"})
  .on('data', function (data, metadata) {
    writer.write(data);
    //importedSaveAs(data, zipName + '.crypt.ziop');
    console.log(metadata)
    })
  .on('error', function (e) {
    writer.abort(e);
    })
  .on('end', function () {
    writer.close();
    })
  .resume();
```

**Comment by jimmywarting** [comment]
It could also be b/c of the zip library you use...

maybe try out my own streaming zip library
https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/zip-stream.js
got an example here: https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/saving-multiple-files.html

**Comment by morula** [comment]
> It could also be b/c of the zip library you use...
> 
> maybe try out my own streaming zip library https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/zip-stream.js got an example here: https://github.com/jimmywarting/StreamSaver.js/blob/master/examples/saving-multiple-files.html

Thank you very much. That works. 

Do you have another corresponding ZIP solution with encryption or a hint?

**Comment by jimmywarting** [comment]
sry, don't have any encryption solution

**Comment by morula** [comment]
Solution with the proposed streaming zip library works
