### ISSUE TITLE
Handle cancel on the browser

### ISSUE THREAD

**Issue by Tzvetelin88** [jimmywarting/StreamSaver.js#309]
Is there a way to handle cancelation on the browser?

We start downloading a file, but at some point we click cancel on the browser and we get this:

<img width="981" alt="image" src="https://user-images.githubusercontent.com/9692941/225352636-f52bb861-1ac1-4d6b-b978-599e7b0efe91.png">

where
```ts
writer.write...
writer.close
```
are not handled properly on my end:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/9692941/225352920-669f5e7c-fd0d-4744-820e-0f5c9cc9be18.png">

**Comment by Tzvetelin88** [comment]
Actually I thing I just need to do:
```ts
writer.write(new Uint8Array(data.bufferData)).catch(() => {
         .....
          writer.abort;
        });
```
and to emit signal to backend to do abort() on the readableStream

**Comment by jimmywarting** [comment]
If you do have control over the server then i do recommend to use server tech to save a file rather then relying on StreamSaver.js which is intended for huge data generated on the client side, such as a camera recording. 

all streamsaver really dose is emulating how a server traditionally saves a file using a service worker to emulate what browser/server have traditionally done for years

**Comment by Tzvetelin88** [comment]
Yes, I'm actually doing that on the server side. Using NodeJS fs to R/w files.
I'm using StreamSaver.js on the client side, as downloading files is causing browser to crash.
I did this implementation - https://github.com/Tzvetelin88/very-big-file-upload-download

StreamSaver works very well on the client side, which I was missing from long time and how to control big file download.
