### ISSUE TITLE
Rename a WritableStream

### ISSUE THREAD

**Issue by FloatingMind12** [jimmywarting/StreamSaver.js#316]
Is there a way to rename a WritableStream after it has already been created and has data writen into?

**Comment by jimmywarting** [comment]
Nope.

You could only do this with the native [file system access](https://github.com/WICG/file-system-access/) which is only available in Blink

**Comment by jimmywarting** [comment]
Uhm, you can't exactly copy a file after it have been writen.
StreamSaver.js don't have any access what so ever to the disk. it acts more or less how a regular file is downloaded from a server. 1) You click on a link. 2) the thing can't be rendered, so it fallbacks to saving the file. 

file name is adjusted with content-disposition attachment response header.


You could `tee` the stream and write it to two destinations. 
but you would have to create two downloads for it.

```js
const dest1 = streamSaver.createWriteStream('a.txt')
const dest2 = streamSaver.createWriteStream('b.txt')

// Get a readable stream somehow, somewhere
const readable = new Response('foobar').body

// clone the stream
const [readable1, readable2] = readable.tee()

readable1.pipeTo(dest1)
readable2.pipeTo(dest2)
```
