### ISSUE TITLE
Local test doesn't work in chrome

### ISSUE THREAD

**Issue by ianopolous** [jimmywarting/StreamSaver.js#33]
I tried out the local test in Chromium 53. 
Attempting the text example leads to:
"Uncaught (in promise) DOMException: Failed to get a ServiceWorkerRegistration: The user denied permission to use Service Worker."

There was no request for any permission.

**Comment by jimmywarting** [comment]
Hmm, tuff question. 
- Try changing 'https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=' + to local url?
- Have you disallowed 3th party cookies? Think it could be a reason for some weird reason
- Are you testing it from a secure origin with valid ssl or localhost?

**Comment by ianopolous** [comment]
This was from localhost. 
Changing the mitm url to localhost fixes the problem. Thank you for your help.

**Comment by tentelemed** [comment]
Hmm doesn't work for me :(
I moved both mitm sw.js and the StreamSaver.js to local (only the polyfill remains external) and I still get the following : 

Failed to register/update a ServiceWorker for scope ‘http://localhost:8080/quickstart_war_exploded/’: Bad Content-Type of ‘text/html’ received for script ‘http://localhost:8080/quickstart_war_exploded/sw.js’.  Must be a JavaScript MIME type.
SecurityError: The operation is insecure.

**Comment by jimmywarting** [comment]
then you are serving the wrong content-type for sw.js
