### ISSUE TITLE
The browser will crash when downloading files exceeding 2G through fetch

### ISSUE THREAD

**Issue by SakuraYou** [jimmywarting/StreamSaver.js#336]
$start.onclick = () => {
        const url = 'xxxx', // a 2gb size file
        const fileStream = streamSaver.createWriteStream('cat.mp4')

        fetch(url).then(res => {
          const readableStream = res.body

          // more optimized
          if (window.WritableStream && readableStream.pipeTo) {
            return readableStream.pipeTo(fileStream)
              .then(() => console.log('done writing'))
          }

          window.writer = fileStream.getWriter()

          const reader = res.body.getReader()
          const pump = () => reader.read()
            .then(res => res.done
              ? writer.close()
              : writer.write(res.value).then(pump))

          pump()
        })
      }

**Comment by jimmywarting** [comment]
Browser?

**Comment by SakuraYou** [comment]
> Browser?

yes！

**Comment by jimmywarting** [comment]
I mean... what browser & version are you using to cause a crash?

**Comment by SakuraYou** [comment]
Sorry, it’s my problem. A colleague here rewrote the fetch method, causing memory accumulation.
