### ISSUE TITLE
invalid error: [StreamSaver] You didn't send a messageChannel

### ISSUE THREAD

**Issue by tra4less** [jimmywarting/StreamSaver.js#338]
Streamsaver focuses messages generated by other libraries, causing invalid error

https://github.com/jimmywarting/StreamSaver.js/blob/5b372f7ba5f1e82ef80e2466023930ee2c616a28/mitm.html#L61-L71

**Comment by JYbill** [comment]
#234 
I have solved the problem in this way, maybe you can try it.

**Comment by caenderl** [comment]
The download works and if this error would appear only once on console, it would be okay. But it prints the error like crazy and my only workaround at the moment is a page reload after the download which is definitely not a solution.
Happy for any possibly better workaround or a solution.
