### ISSUE TITLE
Timeout (?) on writing file with webtorrent

### ISSUE THREAD

**Issue by rotarui** [jimmywarting/StreamSaver.js#37]
Hi, 
got this error where I try to write the document I'm downloading from webtorrent slowly as he downloads, the write stream just crashes (download says "Failed - Network error"). I also tried to write it all as he ends downloading but the file is way to big and page crashes :/ Any idea on how I could write this damn 1.5 gb buffer into a file ?

**Comment by jimmywarting** [comment]
Are you downloading 1 or many files?
Some bit of code sample would help also

**Comment by rotarui** [comment]
I'm seeding from a homemade server a 1.5gb file (binary style). The upload speed is 100kb/s (when I'm on my network it's 3mb/s). What I do on client side is : 
```
let fileStream = streamSaver.createWriteStream(file.name, file.size)
let writer = fileStream.getWriter()
file.createReadStream()
.on('data', data => writer.write(data))
.on('end', () => writer.close())
```
the file variable as been defined as `var file = downloader.torrents[0].files[0]` where downloader is my webtorrent client.What this does is that it starts downloading and seems to end upon a certain time (not a certain size). When I downloaded with 100kb/s , I went up to 200mb, and with 3mb/s to 500mb.
<img width="213" alt="screen shot 2016-10-27 at 09 57 20" src="https://cloud.githubusercontent.com/assets/17824082/19759132/ce2872c8-9c2b-11e6-8a95-1aac5e490c11.png">
This is what it looks like when it fails.

**Comment by jimmywarting** [comment]
Hmm, never tried such large torrent file before

Perhaps not the solution, but I think you need a [Custom chunk store](https://webtorrent.io/docs#-client-add-torrentid-opts-function-ontorrent-torrent-) also. Otherwise WebTorrent still keeps the data in memory in order to seed to other peers. Even if it means that everything is being written to a black hole.

My streamSaver lib has nothing like a timeout...

**Comment by rotarui** [comment]
So even if I can fully download the variable (And I see it fully loaded) , there is no way I could save it (even if not fast) ? . I'll take a look at the Custom chunk store but I would love to have them seeding everything they have downloaded :/ Thanks

**Comment by jimmywarting** [comment]
Are there times when streamsaver is idle? like no data are being written for a while?

**Comment by rotarui** [comment]
Yes ! There is a very weird think with webtorrent where It loses the server peer for approx 2 mins. It happens twice on the full download and it always happen at the exact same moment .

**Comment by jimmywarting** [comment]
Just tried my [demo](https://jimmywarting.github.io/StreamSaver.js/example.html) page where i put a download idle for a few minutes.

I'm guessing if there is nothing being written durning a while it crashes :(

**Comment by rotarui** [comment]
Ok, i'll try to add the peer manually as soon as the server gets discovered. Hope it'll work !

**Comment by jimmywarting** [comment]
Guess the solution otherwise is to have a few bytes buffered up like (don't write this last 5 mb - if nothing gets written durning 1 minute take 1 mb from the pool to keep the download stream alive)

**Comment by rotarui** [comment]
The thing is that as this is only for testing , my server is at my home, using my internet (which is awful as you see I have 100kb upload). As soon as I test this with a friend and he's got a real network on which he downloads, I'll start downloading really faster and without interruption. I'll test buffered writting too, thanks for your help !

**Comment by rotarui** [comment]
Isn't there any method I could use to "pause" the writter ?

**Comment by jimmywarting** [comment]
Have you found a solution?

**Comment by rotarui** [comment]
No, nothing seemed to work , I tried to set up my own tracker to keep the download as stable as I can, but it still occured that the download stops for a few seconds. But I found an alternative for big files : IPFS. Thanks for your help !
