### ISSUE TITLE
Import failure on es6 with "import { createWriteStream } from 'StreamSaver'"

### ISSUE THREAD

**Issue by kevinguard** [jimmywarting/StreamSaver.js#40]
When adding this to client-side code:
```
import { createWriteStream } from 'StreamSaver';
```
I keep getting the following error:
```
[size, queuingStrategy] = [queuingStrategy, size]
^^^^^^^^^^^^^^^^^^^^^^^
ReferenceError: Invalid left-hand side in assignment
```
I'm using es6. Is there something else I need to worry about? This seems to me the most reasonable way to import module and the utility methods. Thanks!

**Comment by jimmywarting** [comment]
Hmm, I'm simply doing [variable swapping](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Swapping_variables) - nothing wrong with that

What browser are you testing?
could it be something wrong with require.js? or any other of you build process?

It's valid syntax

Dose this work:

```js
function bar(){
  "use strict"
  function foo(a, b) {
     [b, a] = [a, b]
     console.log(a) // 2
  }

  foo(1,2)
}
bar()
```

**Comment by kevinguard** [comment]
@jimmywarting I am testing this on Chrome. Also, I don't use require.js. I simply do import as stated above. Interestingly, the following works:
```
import { saveAs } from 'file-saver';
```
And yes, variable swapping as in your example snippet works flawlessly.

**Comment by jimmywarting** [comment]
Then how can you use import? It's not supported in any browser...

**Comment by kevinguard** [comment]
I use webpack. Actually I was going to ask you if this is supported in webpack or not?

**Comment by jimmywarting** [comment]
Maybe try updating node version if you haven't done that
