### ISSUE TITLE
Electron/Ember app

### ISSUE THREAD

**Issue by melquic** [jimmywarting/StreamSaver.js#41]
Hi,

I'm trying to use StreamSaver in an Electron/Ember app.

install:
npm install streamsaver --save-dev
npm install web-streams-polyfill --save-dev

import:
import { createWriteStream, supported, version } from 'npm:StreamSaver';

but when I try to use it:
const fileStream = streamSaver.createWriteStream('filename.txt');

 I get an error:
Uncaught ReferenceError: streamSaver is not defined

Any ideas?
thank you!

**Comment by derhuerst** [comment]
You import `createWriteStream`, `supported` & `version` directly, so `streamSaver` won't be defined. Decide on one of the two:

```js
import { createWriteStream, supported, version } from 'npm:StreamSaver';
const fileStream = createWriteStream('filename.txt');
```

```js
import streamSaver from 'npm:StreamSaver';
const fileStream = streamSaver.createWriteStream('filename.txt');
```

**Comment by melquic** [comment]
Thank for reply.
I already tried to import like this:

`import streamSaver from 'npm:StreamSaver';
const fileStream = streamSaver.createWriteStream('filename.txt'); `

I get this error:
Uncaught TypeError: Cannot read property 'createWriteStream' of undefined

**Comment by derhuerst** [comment]
`WritableStream` is part of [`stream`](https://nodejs.org/api/stream.html). I'm not that familiar with Electron, but you may need a `stream` implementation/polyfill, e.g. [`stream-browserify`](https://github.com/substack/stream-browserify).

**Comment by melquic** [comment]
Thanks!
