### ISSUE TITLE
'dangerous use of the global this object' from the Closure compiler

### ISSUE THREAD

**Issue by rickyclarkson** [jimmywarting/StreamSaver.js#42]
Hi, I'm just trying out StreamSaver.js, and I'm a relative novice at JavaScript. Our build system compiles code using the Closure compiler, and I gather this is normally a warning but for us it's an error. 

this[name] = definition() inside one of the lambdas seems to give this error, as flattening could change which 'this' object is modified by this call. If you don't want to fix it could you please explain what object this should be there, and I can have a go?

**Comment by jimmywarting** [comment]
I'm only using ‘this‘ in one place in the code...
Do you have any alternative solution to do it? Would ‘self‘ work?

I don't know so much about closure compiler. PR is welcome
