### ISSUE TITLE
Investigate 206 partial download

### ISSUE THREAD

**Issue by jimmywarting** [jimmywarting/StreamSaver.js#46]
One issue service worker have is a hard 5 minutes to live before it restarts/shutdown to defend itself from malicious code that drains ram and memory leaks.

In order too work around it I though about "What if we could resume the download"

I think it might work. Firefox don't have ReadableStream, so by using partial response i think we can get grate support for all browsers that supports service workers since it's just basic http

- [ ] Test to see if partial download works
- [ ] Test if unknown length is acceptabel
- [ ] Test to see if the download can recover from service workers reboot (after 5m)
- [ ] Use partial response instead of ReadableStream in service worker or use both?
- [ ] Add a support for accept bytes range on all downloads

**Comment by gladkikhartem** [comment]
I've tried generating 206 response in service-worker, but not luck - Chrome gives me **Failed - No file error**.
```
headers = {
		'Content-Type': 'application/octet-stream; charset=utf-8',
		'Content-Disposition': "attachment; filename*=UTF-8''" + filename,
        'Content-Range' : 'bytes 0-20/20',
        'Content-Length' : '20'
	}
    var resp = new Response("12345678901234567890", {status:206, headers:headers })
	event.respondWith(resp)
```
Neither I found any support for 206 message for Chrome.

**Comment by guest271314** [comment]
@gladkikhartem Missing `=` at `bytes=0-20/20`? See also https://github.com/whatwg/fetch/issues/556#issuecomment-310846807, https://github.com/whatwg/fetch/pull/560

**Comment by gladkikhartem** [comment]
In contrast to Range header - Content-Range header is written without =  
The comments you provided are for Sending Range request to server, rather than Giving Content-Ranger response from service worker.
The only workaround I've found is to open "Development Tools" - then service worker will run without 5 minutes limitation.

**Comment by jimmywarting** [comment]
The idea was that it was meant to break the download, browsers can handle the reconnection.

- say you got a filesize that is 150 mb
- you download as much as you can until the connection breaks
- browser know it supports range request so you resumes where you left of
  it will then make a new request to the service worker with a byte range request
- then you respond with a partial 206 response

That way service worker can be able to restart. But it seems like there is a better solution. 

>> In my case I think as long as the website with the same scope has a MessageChannel shared with the service worker it would be wrong to terminate the service worker

> This usecase is already handled by shared workers.

https://github.com/WICG/background-fetch/issues/39#issuecomment-307337642

Maybe I'm doing it wrong?
The MessageChannel isn't from the same scope

**Comment by gladkikhartem** [comment]
`The idea was that it was meant to break the download, browsers can handle the reconnection.`
According to https://cs.chromium.org/chromium/src/content/browser/download/download_item_impl.cc?sq=package:chromium&l=1007 the only error when chrome resumes download automatically is when local file is different length from the file downloaded. I've played with Content-Lenght and Content-Range headers, but without any results :(

**Comment by jimmywarting** [comment]
Have a solution for this that involves pinging the sw every 4.5 min

**Comment by AndySpider** [comment]
@jimmywarting Any update or possible solution to support download resuming?
I had such a requirement recently and my basic idea is also to try the 206 code and range headers. 

What I expect is that Browser can send request with **Range** header when download a previously failed file. Then I can known that it's trying to resume and where it wants to start. 

I did some testing in Chrome and found that,
For a normal case with a backend server, that's the case when the server responds with  "Accept-Ranges", "Content-Length" and "Etag"/"Last-Modified" headers. 
But when SW is involved, Chrome never sends **Range** header. Also on the network inspector it shows a warning "Provisional headers are shown".
Even negative when the download is triggered dynamically by creating an iframe (either with or w/o SW), no **Range** header will be sent.
