### ISSUE TITLE
Possibility to detect interrupted downloads

### ISSUE THREAD

**Issue by gladkikhartem** [jimmywarting/StreamSaver.js#47]
Dear **jimmywarting**,

The StreamSaver is a really awesome tool, It allows to do things that are not achievable by other libraries.
I'm using it to save a lot of data and had a few non-critical issues.

1.
When I close the page - the download continues and never shuts down.
Is there's any theoretical possibility to detect existing "open" stream-saver sessions or recover them?
I'm seeking for your advice.

2.
 When I supply wrong-type object to write function - the code just fails without any explanations. I've tried many solutions, including placing sw.js on my own webserver. Finally I've found issue that I've supplied wrong object to the function :). I think simple type-detection would help a lot for freshmen.

**Comment by jimmywarting** [comment]
1. 
You should close the stream before you close the tab. 
It's possible with the onbeforeunload event

```js
writer = fileStream.getWriter()
window.onbeforeunload = event => writer.abort()
```

Atm there is no way to recover a download. but I think i might have a solution to that: tracked here #46

2
it could benefit a little from type detection, What function were you referring to?

**Comment by gladkikhartem** [comment]
Than you for mentioning **window.onbeforunload**, this will be enough for me.
About partial content - this sounds really cool, especially when it comes to cross-browser compatibility.
Regarding #46 issue - I had no problems with 5 minutes limit for the service-worker and saved 8 GBs of data in 45 minutes on Chrome 56.  

**writer.write(arraybuffer)** which I replaced with **writer.write(new Uint8Array(arraybuffer))** and it worked
