### ISSUE TITLE
ReferenceError: WritableStream is not defined

### ISSUE THREAD

**Issue by lboff** [jimmywarting/StreamSaver.js#49]
Hello,
I am working on a js react application using webpack.
I installed the npm:
`npm install streamsaver`

In the file where I am using the feature I imported the streamSaver
```javascript
import streamSaver from 'streamsaver';
```

In the code I added
```javascript
let fileStream = streamSaver.createWriteStream('teststream.csv');
let writer = fileStream.getWriter();
```

As soon as the code try to create the WriteStream I have the following error:
```
uncaught at appSaga 
 at takeEvery 
 at callApiReadExport 
    ReferenceError: WritableStream is not defined
    at Object.createWriteStream (webpack:///./~/StreamSaver/StreamSaver.js?:89:3)
    at callApiReadExport$ (webpack:///./app/containers/App/sagas.js?:347:77)
    at tryCatch (webpack:///./~/regenerator-runtime/runtime.js?:63:40)
```

Where I am making a mistake?

**Comment by lboff** [comment]
I changed a bit the code.
```javascript
import { createWriteStream, supported, version } from 'StreamSaver';
...
  console.log('---> supported',supported);
  console.log('---> version',version);
  let fileStream = createWriteStream('teststream.csv');
  let writer = fileStream.getWriter();
```
In the console I have:
```
---> supported true
---> version Object {full: "1.0.0", major: 1, minor: 0, dot: 0}
```

The createWriteStream fails with the same error.

**Comment by jimmywarting** [comment]
Hmm, the supported variable produce fallsly value
It only checks if readablestream is supported (which the service worker need) the writeable stream however is not supported by any browser yet. But is not required to support a streaming download. 

However streamsaver was built with both readablestream and writeablestream in mind... So the easiest way fix it yourself now is to include the stream polyfill

**Comment by lboff** [comment]
I am not understanding. I need to download a stream and I followed the example using **createWriteStream** which rise the error because of writable stream.
If writeable stream is not required for streaming download how I can avoid to use it?

**Comment by jimmywarting** [comment]
You can not avoid writeablestream as it's right now. You need the polyfill
