### ISSUE TITLE
Illegal Constructor error loading example.html

### ISSUE THREAD

**Issue by johanaita87** [jimmywarting/StreamSaver.js#5]
Uncaught TypeError: Illegal constructor
ReadableStream	@	native ReadableStreamTempStub.js:8
$form.onsubmit.event	@	example.html:49

**Comment by jimmywarting** [comment]
Have you enabled experimental javascript flags in chrome?

**Comment by johanaita87** [comment]
Experimental javascript flag is enabled

**Comment by jimmywarting** [comment]
hmm, sorry, it wasn't experimental javascript
it is experimental web platform features... chrome://flags/#enable-experimental-web-platform-features

**Comment by johanaita87** [comment]
it is enabled as well...! is this working for you using Chrome?

**Comment by jimmywarting** [comment]
Yes...

**Comment by jimmywarting** [comment]
I have recently updated the public api... it now depends on a stream polyfill... but still needs native ReadableStream in the service worker

**Comment by jimmywarting** [comment]
It depends on stream polyfill now.
I wanted the public api to expose a writable stream, and gotten ReadableStream constructor to work as a bonus.

Constructing the native ReadableStream is only going to work on chrome v52 so...

To check if it's supported you should do: `alert(streamsaver.supported)`
