### ISSUE TITLE
Firefox!

### ISSUE THREAD

**Issue by DannyZB** [jimmywarting/StreamSaver.js#57]
https://bugzilla.mozilla.org/show_bug.cgi?id=1128959

**Comment by jimmywarting** [comment]
Awesome!

**Comment by strategeens** [comment]
So, can i test it on Firefox nightly?

**Comment by chickahoona** [comment]
Any update here?

**Comment by chickahoona** [comment]
Im very sad that this got closed without comment

**Comment by DannyZB** [comment]
Me and Jimmy did some testing.

Firefox times out streams after 5 minutes due to how it's design, making it useless until that is changed in the browser.

Works for downloads under 5 minutes

**Comment by chickahoona** [comment]
Thank you very much for this update!

**Comment by DannyZB** [comment]
Leave this open. We can discuss how to make Firefox implement it.
Get the community on it.

Do you have urls of the issues on Mozilla?

**Comment by jericopulvera** [comment]
Did Firefox implemented it already?

**Comment by mrshawn191** [comment]
Sorry if im out of line, but does streamSaver work with firefox or not? 

I am getting some errors in firefox

`Service worker event waitUntil() was passed a promise that rejected with 'ReferenceError: ReadableStream is not defined'.`

**Comment by jimmywarting** [comment]
You can vote for this issues to be fixed over at bugzilla

- [Implement ReadableStream](https://bugs.webkit.org/show_bug.cgi?id=138967) which depends on:
  - [Implement Streams API](https://bugs.webkit.org/show_bug.cgi?id=138561) which also depends on:
    - [Implement WritableStream](https://bugs.webkit.org/show_bug.cgi?id=149842) to be fixed

**Comment by chickahoona** [comment]
Is there an update for this?

**Comment by jimmywarting** [comment]
That seems to be finish, but Firefox has not enabled streams yet. They have many sub-ticket around the stream API that it should be working together with the fetch api, service worker etc

From version 57: this feature is behind the dom.streams.enabled preference (needs to be set to true) and the javascript.options.streams preference (needs to be set to true). To change preferences in Firefox, visit about:config.

**Comment by nascent** [comment]
Seems to be enabled by default in Quantum, but there's no option for dom.streams.enabled in either browser and Quantum doesn't work at this stage, with no error reported

**Comment by jimmywarting** [comment]
it seems to kind of work in v65...

**Comment by DannyZB** [comment]
What does kind of mean?

**Comment by jimmywarting** [comment]
The "Plain text (Save as you type)" example works fine - so it seems to work as it should.
the other examples don't work like the fetch, torrent and audio recording

**Comment by DannyZB** [comment]
Remember the test code we did for fetching empty binary data, does that
work?
That's all that is necessary to download. Also needs to run without failing
for an hour

**Comment by jimmywarting** [comment]
Closing this since i just tested a link from https://github.com/jimmywarting/StreamSaver.js/pull/83#issuecomment-466832404 in FF and it did work
