### ISSUE TITLE
Failed to minify code for production build

### ISSUE THREAD

**Issue by cme0848** [jimmywarting/StreamSaver.js#63]
I've written a webapp using ReactJS and StreamSaver and it works great but am having difficulty in building a production release. 

`npm run build`
`Failed to minify the code from this file: `
` 	./node_modules/streamsaver/StreamSaver.js`

**Comment by cme0848** [comment]
I ran StreamSaver.js through Babel with minify options enabled. It compiles now. 

`'use strict';var _typeof='function'==typeof Symbol&&'symbol'==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&'function'==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?'symbol':typeof a};(function(a,b){'undefined'==typeof module?'function'==typeof define&&'object'==_typeof(define.amd)?define(b):(void 0)[a]=b():module.exports=b()})('streamSaver',function(){'use strict';var b,c,d='https:'==location.protocol||'localhost'==location.hostname,f={createWriteStream:function(g,h,i){if(Number.isFinite(h)){var j=[h,i];i=j[0],h=j[1]}var k=new MessageChannel,l,m=function(){return new Promise(function(n){if(k.port1.onmessage=function(r){if(r.data.download){n(),d||l.close();var s=document.createElement('a'),t=new MouseEvent('click');s.href=r.data.download,s.dispatchEvent(t)}},d&&!b&&(b=document.createElement('iframe'),b.src=f.mitm,b.hidden=!0,document.body.appendChild(b)),d&&!c){var p;b.addEventListener('load',p=function fn(){c=!0,b.removeEventListener('load',p),b.contentWindow.postMessage({filename:g,size:i},'*',[k.port2])})}if(d&&c&&b.contentWindow.postMessage({filename:g,size:i},'*',[k.port2]),!d){l=window.open(f.mitm,Math.random());var q=function(r){r.source===l&&(l.postMessage({filename:g,size:i},'*',[k.port2]),removeEventListener('message',q))};addEventListener('message',q)}})};return new WritableStream({start:function start(){return m()},write:function write(n){k.port1.postMessage(n)},close:function close(){k.port1.postMessage('end'),console.log('All data successfully read!')},abort:function abort(){k.port1.postMessage('abort')}},h)},supported:!1,version:{full:'1.0.1',major:1,minor:0,dot:0}};f.mitm='http://localhost:3002/streamsaver/mitm.html?version'+f.version.full;try{f.supported='serviceWorker'in navigator&&!!new ReadableStream&&!!new WritableStream}catch(g){}return f});
`

**Comment by jimmywarting** [comment]
Just a tip, when you post code on github issues (markdown) wrap it around three backtickets `` ` `` followed by the coding language for proper syntax color
`````js
```js
code
```
`````

`````js
```html
<code>
```
`````
