### ISSUE TITLE
Check if file was saved and not aborted [REPOST from FileSaver]

### ISSUE THREAD

**Issue by perezale** [jimmywarting/StreamSaver.js#66]
Is there a current way to check if the user really DID save the file and not click cancel after the saveAs window opened?

Note: This is a repost from FileSaver repo.
That thread mentions that it'd be supported in StreamSaver but it's not firing either the close nor abort handlers.

@defelippe

**Comment by jimmywarting** [comment]
closing as dup of https://github.com/jimmywarting/StreamSaver.js/issues/13

Bottom line is: It should be possible but chrome has a bug and don't report back to service worker when user canceled the download

https://bugs.chromium.org/p/chromium/issues/detail?id=638494
