### ISSUE TITLE
Chrome no longer downloading 😅

### ISSUE THREAD

**Issue by Zwerge** [jimmywarting/StreamSaver.js#72]
Not sure why this is, implemented this a couple of weeks ago, but all of a sudden as of today the file no longer appears as downloaded. 

Not from demo, not from my app

**Comment by jimmywarting** [comment]
It was working for me on my demo page: https://jimmywarting.github.io/StreamSaver.js/example.html

try restarting your browser?
know that FileSaver.js have had some problem durning browser update but was easily fixed with a browser restart

**Comment by Zwerge** [comment]
Huh, that really is strange sry about that!
