### ISSUE TITLE
Console log sw.js:54

### ISSUE THREAD

**Issue by msmicker** [jimmywarting/StreamSaver.js#78]
I have streamsaver incorporated into my project and it is working; however, I get all of these console.log messages. Any ideas what these are from? Thanks in advance.

It is a react project from create react app. I tried two methods to use. Installing by npm and importing in my project. And using a script tag to a cdn hosting of streamsaver. Both result in the same messages.

**Comment by msmicker** [comment]
Apologies, I missed to post examples:
Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.7041366103077649
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/example.html
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/StreamSaver.js
sw.js:54 Handleing  https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js
sw.js:54 Handleing  https://rawgit.com/jimmywarting/browser-su/master/build/permissions.js
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.8063090688496399
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.6575326707611275
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.2644047912007301
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.8896137514853428
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.3234056172793167
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.7827840415191052
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.4134439171630615
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.8927524412151893
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.6771130711041999
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.3721425638518392
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.13887295947393463
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.41383636985939476
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.8359876407765765
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.6868023947471398
react-dom.development.js:15374 Download the React DevTools for a better development experience: https://fb.me/react-devtools
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
StreamSaver.min.js:115 All data successfully read!
Download.jsx:38 Closed the stream, Done writing
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.8493669781039486
StreamSaver.min.js:52 Resource interpreted as Document but transferred with MIME type application/octet-stream: "https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.8493669781039486".
channel.port1.onmessage.evt @ StreamSaver.min.js:52
6client?cd17:80 [WDS] App updated. Recompiling...
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/mitm.html?version=1.0.0
sw.js:54 Handleing  https://jimmywarting.github.io/StreamSaver.js/intercept-me-nr0.37043740249386525

**Comment by jimmywarting** [comment]
Should disappear now.

**Comment by msmicker** [comment]
Thanks, the logging is removed, but now I am getting a strange issues where txt files downloaded are truncated to different levels (repeat downloading for testing). I have a variety of files from small to large (GB). My Test file is ~170KB and shows 152KB, 156KB, etc

The issue may have been there before.

**Comment by jimmywarting** [comment]
Dosen't sound like a StreamSaver issue to me.
If you show some code i might be able to help

**Comment by msmicker** [comment]
Thanks. It’s almost a straight cut/paste from the Ajax example. I thought
it might be my API and wrote some scripts to stress test via curl- not to
say it eliminates the possibility.
