### ISSUE TITLE
Download slows when tab is not in focus

### ISSUE THREAD

**Issue by gannons** [jimmywarting/StreamSaver.js#79]
I've been testing StreamSaver.js using the example.html. I noticed that if the example.html tab is selected it takes ~2 seconds to download 100 Mb. But if I switch to another tab, after a bit of time, the download speed drops to ~1 minute 40 seconds for 100 Mb. If I switch back to the tab the download speed improves. This was measured when downloading 10 - 20 Gb of text.

Is this known? I assume Chrome is reducing the resources its provides to background tabs. But, in this case, that'll introduce usability issues.

**Platform:** Mac OSX 10.14.3
**Chrome:** 71.0.3578.98 (Official Build) (64-bit)

**Comment by jimmywarting** [comment]
might show the code you are using?

if you have a setTimeout or setInterval somewhere it will slow down a bit

**Comment by gannons** [comment]
I'm not using any code @jimmywarting. This is from playing with the example.html

https://github.com/jimmywarting/StreamSaver.js/blob/master/example.html

1. Plain text (Save as you type)
2. Write a lot of Lorem ipsum
3. 10240

I assume everything else is based on Chrome defaults.

**Comment by jimmywarting** [comment]
And there it's

https://github.com/jimmywarting/StreamSaver.js/blob/c3ec89211230a00934b16f5f4e91cf9ff174a47c/example.html#L100-L111

```js
setTimeout(pump)
```

It's just in the demo code, if it would go away it would save a lot faster, there is no setTimeout or setInterval in the streamsaver lib - just in the example file

**Comment by jimmywarting** [comment]
So it's not really an issue

**Comment by gannons** [comment]
Removing the timeout seems to have worked. Though I did notice slight performance issues that were not present before. However that is not part of this issue.

Looks like Chrome, by design, slows down time for background tabs. Found a stackoverflow question about this

https://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs

**Comment by jimmywarting** [comment]
I'm well aware of the background timer 😉
