### ISSUE TITLE
Add option for content length in createWriteStream

### ISSUE THREAD

**Issue by qgustavor** [jimmywarting/StreamSaver.js#8]
It would enable showing the save progress.

*Well... maybe it was already planned.*

**Comment by jimmywarting** [comment]
It is planned 😉 
Trying to figure out what the spec says about [queuing strategy](https://streams.spec.whatwg.org/#ws-constructor)... I think I'm going to support that as well. presumably as second argument.

`new WritableStream(underlyingSink = {}, { size, highWaterMark = 0 } = {})`

I belive size here means something other the content-length in that context

Have any suggestion?
`createWriteStreams('filename', queuingStrategy, contentLength)`?

**Comment by jimmywarting** [comment]
Could maybe do type checking on the arguments. Use whichever argument that's a integer as content length and take the queuing strategy as strategy. Then the order you pass them doesn't matter

**Comment by jimmywarting** [comment]
createWriteStreams('filename', contentLength)

**Comment by Datamancer1110** [comment]
It doesn't look like the fix worked. I specified "3785848" as the second parameter to `StreamSaver.createWriteStream` for my 3.5ish MB file, and I still got the indeterminate-sized download in Chrome. I'm using the latest.

**Comment by jimmywarting** [comment]
Hmm. It did work for me just now with the latest without any changes, just went to the demo and typed this in the console:

```javascript
const writeStream = streamSaver.createWriteStream('filename.txt', 3333333)
const encoder = new TextEncoder
let data = 'a'.repeat(1111111)
let uint8array = encoder.encode(data + "\n\n")

writeStream.write(uint8array)
```
Result: `1,1/3,2 MB 5 sec left`

The service worker can be hard cached sometimes and needs to be removed/updated manually.
Did notice if you paused the download for ~7 sec it will remove the time left.
Another thing was that you have to write `x` amount of bytes for the downloader to start showing some useful information in the beginning it's just like "pending" "starting to download" "trying to estimate the speed by data received over time x"

**Comment by jimmywarting** [comment]
q@Datamancer1110 How did it turn out, did you solve it?

**Comment by Datamancer1110** [comment]
I can't say just yet, as now I'm having trouble getting Chrome to work at all (I'm getting "WritableStream is not defined" even though I have the Experimental feature turned on and I loaded the Polyfill, so I'm not sure what's going on right now)
