### ISSUE TITLE
Detect failure to launch

### ISSUE THREAD

**Issue by KCErb** [jimmywarting/StreamSaver.js#85]
Short version of question:
This is probably answered by / strongly related to #13. But I'm wondering about the case where a user doesn't have a default download location so Chrome brings up a dialog. If they close / cancel that dialog, is there any way to tell?

Long version of question:
To be clear, this is distinct from #13 in that I'm not too worried about them canceling a stream to a file. I can live with that, but I *am* worried about my app thinking it established a connection when it never did. That could be confusing for a new user who doesn't realize that this is a required step since I have no way for my form's `disabled` state to trigger off of this write stream getting initialized properly.

**Comment by jimmywarting** [comment]
The question seems to be about discarding the save dialog and not the cancel event...

Don't think it will ever be possible, you see: the browser starts downloading the files even before the save dialog appear. Also while you are figuring out where you want to save the file, browser will continue to download the content in the background into a buffer/memory

However it might be possible later with the native-filesystem where you can ask for a filesystem entry where you want to save the file. basically you ask where to save it first then you write a stream of data

**Comment by KCErb** [comment]
Yes it does answer my question, thank you.
