### ISSUE TITLE
Firefox quantum 66.0.2(32bit) does not support WritableStream...

### ISSUE THREAD

**Issue by kska32** [jimmywarting/StreamSaver.js#93]
the firefox version only support readblestream object, the writablestream not supported.

**Comment by kska32** [comment]
ReferenceError: WritableStream is not defined

**Comment by jimmywarting** [comment]
Working on a fix...

**Comment by jimmywarting** [comment]
With FF you need stream-polyfill (ponyfill)

closing as it has been fixed in the master branch or as a dupe out of https://github.com/jimmywarting/StreamSaver.js/issues/88#issuecomment-482740124
