### ISSUE TITLE
Current Opera + HTTP = download popup blocked

### ISSUE THREAD

**Issue by TexKiller** [jimmywarting/StreamSaver.js#95]
It seems the current version of Opera blocks the popup with the download link, even if StreamSaver.js is called from an user interaction.

The <code>mitm.html</code> popup is opened normally, but when it is time to open the popup with the download link it is blocked.

This does not happen on version 40 of the Opera browser, where the download is started as it should.

**Comment by TexKiller** [comment]
I think this might be solved if we use the same popup to start the service worker and to start the download. Doing that would also reduce the number of popups that need to be opened for the download to start, both on HTTP and on background pages on Firefox.

**Comment by jimmywarting** [comment]
> It seems the current version of Opera blocks the popup with the download link, even if StreamSaver.js is called from an user interaction.
>
> The mitm.html popup is opened normally, but when it is time to open the popup with the download link it is blocked.

uh? had to read that 2,3 times... if the mitm.html opens just fine it should work as expected? in the current version the download happens using a hidden iframe on the main thread so there shouldn't be any popup blocker?

Will try to reproduce quickly, Maybe work on a fix tomorrow

**Comment by jimmywarting** [comment]
the download should happen in a iframe to prevent popup blocker.
Maybe something wrong with this if statement?

https://github.com/jimmywarting/StreamSaver.js/blob/28fbafea12da53cbef1f0e3624260204236cfcfd/StreamSaver.js#L95

When i changed it for `if (popUp)` it worked out okey
maybe that if condition should only apply for the mitm? thinking maybe all download should happen using the iframe?

**Comment by jimmywarting** [comment]
Agree with my linter that it's not good to mix `||` and `&&` it's confusing

writing `popUp || ( !firefox && !isSecureContext )` is okey

**Comment by TexKiller** [comment]
The download happens on a popup because the top page is insecure. Chrome doesn't allow a request from the <code><a href="https://developer.mozilla.org/docs/Web/HTML/Element/iframe">&lt;iframe&gt;</a></code> to be intercepted by the Service Worker. I assumed Opera would behave the same way, since they are very similar, but maybe I was mistaken.

If you try to start the download from inside the <code><a href="https://developer.mozilla.org/docs/Web/HTML/Element/iframe">&lt;iframe&gt;</a></code> on HTTP on Chrome, the 404 page is shown.

Since it worked on Opera, we could try to have the <code><a href="https://developer.mozilla.org/docs/Web/HTML/Element/iframe">&lt;iframe&gt;</a></code> on Opera and the popup on Chrome, but that would require yet another browser detection.

**Comment by jimmywarting** [comment]
it worked b/c i didn't test insecure context correctly when i used localhost. also get 404 now

**Comment by jimmywarting** [comment]
The best solution is to re-use the popup. currently i see two solutions

- Should we create a download link (iframe) inside the popup
- or should we navigate to the download link
  `popup.location.href = evt.data.download`

**Comment by TexKiller** [comment]
I don't know which one is best, but we should see if they interfere with the immortal Service Worker bug on Chrome and Opera. If there is a way to use the same popup and still have an immortal Service Worker, that would be best. :)

**Comment by jimmywarting** [comment]
The best thing maybe would just be to embrace the should allow to go idle thingy and transfer the readableStream directly to the download so no postMessage & pinging back and forth has to happen.

Would maybe also like to see the `ping.html` & `ping.js` go away to reduce nth of files.
off-topic question: what purpose dose `ping.html` have? can that not be done from `mitm.html`?

---

I have tried a prof-of-concept version by doing `popup.location.href = evt.data.download` and after a short timeout close the popup - so far i have not encounter any bugs and there is no popup blocking happening in either chrome or opera

**Comment by TexKiller** [comment]
> The best thing maybe would just be to embrace the should allow to go idle thingy and transfer the readableStream directly to the download so no postMessage & pinging back and forth has to happen.

Sure, but for that we would have to have a way to start the Service Worker again when needed. On secure contexts we can do that from the iframe, so it shouldn't matter much, but on HTTP we would need to open another popup just to start the Service Worker.

Maybe we can keep a message port open until all the streams are closed, and then we close the port, stop keeping the SW alive and require another <code>mitm.html</code> to register the Service Worker again.

> Would maybe also like to see the `ping.html` & `ping.js` go away to reduce nth of files in the feature.
> off-topic question: what purpose dose `ping.html` have? can that not be done from `mitm.html`?

<code>ping.html</code>'s only function is to start the Shared Worker and to communicate with it. I guess we could do a big <code>if</code> on <code>mitm.html</code> so it does this or its usual thing, as long as we establish a condition.

> I have tried a prof-of-concept version by doing `popup.location.href = evt.data.download` and after a short timeout close the popup - so far i have not encounter any bugs and there is no popup blocking happening in either chrome or opera

Sounds fine. However, it would be very bad if we were to close this popup with a 10s timeout. That would be 10 seconds of a blank window open.

**Comment by jimmywarting** [comment]
Found out that you can't close the popup directly after you send the "download started" postMessage.
it happens almost immediately. And the StreamSaver is asynchronous. Meaning: you can open a downloadUrl and then close it. The "save as" dialog will not appear until after you have written some amount of data. "Torrent" and "write as" you type fails to bring up the saveAs dialog

What do you think is the best solution for that?
- close the popup when stream is completed?
- close the popup after x bytes have been written?
- build some download progress interface in the popup?

**Comment by TexKiller** [comment]
Well, shit. I hadn't thought about that use case.

I guess one possibility would be to figure out the conditions for triggering the download on each browser and only open the popup when those conditions are met. (e.g.: lets imagine Chrome only does it after 1024 bytes written or the stream is closed, then we wait for one of those conditions to happen and then open the popup - by the way, this is made up, I don't actually know if those are Chrome's conditions).

I think anything else would either modify the download's content or leave a popup open for (possibly) a long time.

Another idea would be to try inserting a lot of filler headers on the response to try and trigger the download from those bytes instead of the download body's bytes.

**Comment by jimmywarting** [comment]
> triggering the download on each browser and only open the popup/start the download when those conditions are met.

if we don't trigger the download right away (on user interaction) then we are back on popup being blocked.

We can't just close the popup after 1024 bytes has been written. We must also wait for the user to pick a path, set filename and hit save. (which we can't detect)

one possible solution is to 
 1. Open the initial pooup that installs sw and transfair the DataChannel. 
 2. sw respond back with a download path.
 3. we then close the initial popup. and open up a new popup that starts the download.<br>
 then the download popup will automatically be closed after hitting save. but then we are also back to being blocked by the popup blocker if we do not redirect the initial popup or opens a hidden iframe in the popup

**Comment by jimmywarting** [comment]
found the best way is to redirect the main window to the download url. but only when x bytes have been written so the page can continue and not interrupt new webrtc connection for example.

**Comment by jimmywarting** [comment]
Would it be better to use 
https://developer.chrome.com/extensions/downloads
instead of chrome.tabs.create?

**Comment by TexKiller** [comment]
Well, we can always just buffer the first bytes without opening the <code>mitm.html</code> popup, and only open it when we have enough bytes to write, then we register the SW and start the download (to avoid the popup blocker). We can shift the id creation to <code>StreamSaver.js</code> if we want to have the download link before receiving the message from the SW, that way we can open both popups at once.

I don't know if the downloads API will work with the SW interception. We can test it.

Redirecting the main window will still close open connections, right? If it is possible to avoid it, I think we should.

What happens when we close the popup before the user selects the destination folder? On Firefox the download proceeds as it should, but I think my Chrome was always configured to save on the Downloads folder by default.

**Comment by TexKiller** [comment]
If we can force the download to start without writing any byte by messing with the headers, that would be ideal.

**Comment by jimmywarting** [comment]
I think i may have found a hack do not having to open any further popups at all after the service worker have been installed  😁 🤪
