### ISSUE TITLE
Download does not continue after tab gets closed

### ISSUE THREAD

**Issue by mmilitzer** [jimmywarting/StreamSaver.js#97]
I really like the idea behind StreamSaver.js because it works well also for very large files and the user experience is not different from "normal" server-side downloads in the sense that the user is shown the "Save As" dialog at the beginning of the download and the download with its progress also shows up in the regular browser download tab. That's awesome!

However, its familiar user experience is also its curse currently. So users will not realize that this is not a "normal" download and will happily close the tab once they see the download is progressing in the browser's download manager. People are just used to that they don't need to keep the tab open when the browser seemingly manages the download. However with StreamSaver.js this doesn't work because the download stops when the tab is closed.

So I think this is a really big problem that prevents StreamSaver.js from being usable in any real project. It would just lead to too much user confusion. And so strangely, I don't see this problem much discussed here (in github issues) even though I think it is so important. 

I realize that this is most likely a browser limitation/bug and I found some related issues in Chromium too that service workers get killed even though they still have a user-facing connection (like a download) open. And while this was acknowledged as undesired, these bugs are unresolved for years now, so it doesn't look like browsers will fix this anytime soon. 

So is there really not any way around this? Any possibility how at least the already running downloads would continue until completion after the tab got closed?

**Comment by jimmywarting** [comment]
I know that it's a problem.

> So is there really not any way around this? Any possibility how at least the already running downloads would continue until completion after the tab got closed?

it depends on what kind of data you are saving...

if you can use **Server side:** Do what StreamSaver tries to emulate, Save the file with the help of the server if the data is coming from a backend and avoid StreamSaver all together. 

The second best would be to **move main thread work to ServiceWorker** This would allow you to at least reload or navigate to another page and also give you a tiny bit of extra time to end the stream. But you also have to keep the service worker alive by pinging it with something like postMessages or fetch. 

But keeping the service worker or tab alive is not always necessary if you manage to transfer a ReadableStream that you don't write anything to. for example:

```js
async downloadUrl (request) {
  const res = await fetch(url)
  const stream = res.body
  const headers = {'Content-Disposition': 'attachment ...'}
  return new Response(stream, { headers })
}

downloadBlob (request) {
  const headers = {'Content-Disposition': 'attachment ...'}
  return new Response(blob, { headers })
}

self.onfetch = evt => {
  evt.respondWith(downloadUrl(evt.request))
}
```

...doing it that way you avoid the need of having both service worker and any tab alive. it's also possible to transfere such a ReadableStream with postmessage to the sw

the last thing you can do is to use [onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) and warn the user that leaving the page will break the download

**Comment by mmilitzer** [comment]
Well, think of saving a big file that's distributed as a torrent like with your webtorrent example. Of course, I could run a torrent client on the server and send down the file fetched on the server-side to the browser as a regular HTTP download. But that would defeat the whole purpose of taking load off the server via P2P communication.

So to save a file through webtorrent in a streaming fashion, webtorrent needs to be running and fetching many individual input pieces from other peers or web seeds and then concatenate them while the data is sent down as one file by the service worker to the client.

Background Fetch looks like an interesting API. But from what I see, it wouldn't solve the task at hand.

- Webtorrent and P2P communication would not work. I can just fetch via HTTP only with Background Fetch (so using "webseeds" in bittorrent terminology).

- I could probably do some kind of mixed mode, so fetch torrent pieces with webtorrent as long as the user has the browser tab open and load the rest with Background Fetch then once the user closed the tab. But from what I see, Background Fetch doesn't support range requests. So it'll be difficult to avoid downloading the same pieces again that were already downloaded by webtorrent.

- Because the service worker will be killed when the user closes the tab and because the Background Fetch happens asynchronously and will trigger the service worker again just once all background fetches are done, the end-user facing download of the final file (concatenated from the many downloaded torrent pieces) cannot happen in a streamable fashion. So I cannot show the file "Save As" dialog already in the very beginning of the download and just stream the data down. 

- Instead, I'd first have to fetch all torrent pieces first and store them somehow (e.g. in indexeddb) to avoid excessive memory usage. And just when all data is fetched, I could prompt the user to save the file. But then it wouldn't look like a "native" download to the user anymore, unfortunately. And also, because the entire data needs be persisted first before it can be saved to the final destination on disk, it's at least temporarily stored twice on the disk. And if the user hasn't enough free disk space so that the browser grants us enough indexeddb quota, the whole thing wouldn't work at all...

So it's unfortunate but most probably nothing better can be done right now than caching everything first in indexeddb and offering the user to save it to a file then just at the very end...

**Comment by mmilitzer** [comment]
Well, think of saving a big file that's distributed as a torrent like with your webtorrent example. Of course, I could run a torrent client on the server and send down the file fetched on the server-side to the browser as a regular HTTP download. But that would defeat the whole purpose of taking load off the server via P2P communication.

So to save a file through webtorrent in a streaming fashion, webtorrent needs to be running and fetching many individual input pieces from other peers or web seeds and then concatenate them while the data is sent down as one file by the service worker to the client.

Background Fetch looks like an interesting API. But from what I see, it wouldn't solve the task at hand.

- Webtorrent and P2P communication would not work. I can just fetch via HTTP only with Background Fetch (so using "webseeds" in bittorrent terminology).

- I could probably do some kind of mixed mode, so fetch torrent pieces with webtorrent as long as the user has the browser tab open and load the rest with Background Fetch then once the user closed the tab. But from what I see, Background Fetch doesn't support range requests. So it'll be difficult to avoid downloading the same pieces again that were already downloaded by webtorrent.

- Because the service worker will be killed when the user closes the tab and because the Background Fetch happens asynchronously and will trigger the service worker again just once all background fetches are done, the end-user facing download of the final file (concatenated from the many downloaded torrent pieces) cannot happen in a streamable fashion. So I cannot show the file "Save As" dialog already in the very beginning of the download and just stream the data down. 

- Instead, I'd first have to fetch all torrent pieces first and store them somehow (e.g. in indexeddb) to avoid excessive memory usage. And just when all data is fetched, I could prompt the user to save the file. But then it wouldn't look like a "native" download to the user anymore, unfortunately. And also, because the entire data needs be persisted first before it can be saved to the final destination on disk, it's at least temporarily stored twice on the disk. And if the user hasn't enough free disk space so that the browser grants us enough indexeddb quota, the whole thing wouldn't work at all...

So it's unfortunate but most probably nothing better can be done right now than caching everything first in indexeddb and offering the user to save it to a file then just at the very end...

**Comment by mmilitzer** [comment]
Well, think of saving a big file that's distributed as a torrent like with your webtorrent example. Of course, I could run a torrent client on the server and send down the file fetched on the server-side to the browser as a regular HTTP download. But that would defeat the whole purpose of taking load off the server via P2P communication.

So to save a file through webtorrent in a streaming fashion, webtorrent needs to be running and fetching many individual input pieces from other peers or web seeds and then concatenate them while the data is sent down as one file by the service worker to the client.

Background Fetch looks like an interesting API. But from what I see, it wouldn't solve the task at hand.

- Webtorrent and P2P communication would not work. I can just fetch via HTTP only with Background Fetch (so using "webseeds" in bittorrent terminology).

- I could probably do some kind of mixed mode, so fetch torrent pieces with webtorrent as long as the user has the browser tab open and load the rest with Background Fetch then once the user closed the tab. But from what I see, Background Fetch doesn't support range requests. So it'll be difficult to avoid downloading the same pieces again that were already downloaded by webtorrent.

- Because the service worker will be killed when the user closes the tab and because the Background Fetch happens asynchronously and will trigger the service worker again just once all background fetches are done, the end-user facing download of the final file (concatenated from the many downloaded torrent pieces) cannot happen in a streamable fashion. So I cannot show the file "Save As" dialog already in the very beginning of the download and just stream the data down. 

- Instead, I'd first have to fetch all torrent pieces first and store them somehow (e.g. in indexeddb) to avoid excessive memory usage. And just when all data is fetched, I could prompt the user to save the file. But then it wouldn't look like a "native" download to the user anymore, unfortunately. And also, because the entire data needs be persisted first before it can be saved to the final destination on disk, it's at least temporarily stored twice on the disk. And if the user hasn't enough free disk space so that the browser grants us enough indexeddb quota, the whole thing wouldn't work at all...

So it's unfortunate but most probably nothing better can be done right now than caching everything first in indexeddb and offering the user to save it to a file then just at the very end...
